### ISSUE TITLE
TypeError: string argument expected, got 'NoneType' 

### ISSUE THREAD

**Issue by stevencollinscn** [kylebarron/stata_kernel#124]
Trying to install the kernel on Windows 10 and encountered the following issues:

```
Microsoft Windows [Version 10.0.17134.228]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\liqia>pip install stata_kernel
Collecting stata_kernel
  Using cached https://files.pythonhosted.org/packages/d4/55/39b8359974cc83dd1d4c123a389cef790a5e92c644e45b955ba832f0e815/stata_kernel-1.4.1-py3-none-any.whl
Requirement already satisfied: pygments>=2.2.0 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (2.2.0)
Requirement already satisfied: pillow>=5.2.0 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (5.2.0)
Collecting pexpect>=4.6.0 (from stata_kernel)
  Using cached https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl
Requirement already satisfied: beautifulsoup4>=4.6.3 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (4.6.3)
Requirement already satisfied: ipykernel>=4.8.2 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (4.8.2)
Collecting regex>=2018.7.11 (from stata_kernel)
  Using cached https://files.pythonhosted.org/packages/15/a5/cdb73862c207dcbb2dec5a4c64f850314910c55097dfa12cdfc533892502/regex-2018.08.29-cp36-none-win_amd64.whl
Requirement already satisfied: jupyter-client>=5.2.3 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (5.2.3)
Requirement already satisfied: pandas>=0.23.4 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (0.23.4)
Requirement already satisfied: IPython>=6.5.0 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (6.5.0)
Collecting ptyprocess>=0.5 (from pexpect>=4.6.0->stata_kernel)
  Using cached https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: traitlets>=4.1.0 in c:\users\liqia\anaconda3\lib\site-packages (from ipykernel>=4.8.2->stata_kernel) (4.3.2)
Requirement already satisfied: tornado>=4.0 in c:\users\liqia\anaconda3\lib\site-packages (from ipykernel>=4.8.2->stata_kernel) (5.1)
Requirement already satisfied: jupyter_core in c:\users\liqia\anaconda3\lib\site-packages (from jupyter-client>=5.2.3->stata_kernel) (4.4.0)
Exception:
Traceback (most recent call last):
  File "c:\users\liqia\anaconda3\lib\site-packages\pip\_internal\basecommand.py", line 141, in main
    status = self.run(options, args)
  File "c:\users\liqia\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "c:\users\liqia\anaconda3\lib\site-packages\pip\_internal\resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\users\liqia\anaconda3\lib\site-packages\pip\_internal\resolve.py", line 261, in _resolve_one
    check_dist_requires_python(dist)
  File "c:\users\liqia\anaconda3\lib\site-packages\pip\_internal\utils\packaging.py", line 46, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "c:\users\liqia\anaconda3\lib\email\feedparser.py", line 175, in feed
    self._input.push(data)
  File "c:\users\liqia\anaconda3\lib\email\feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'

**Comment by stevencollinscn** [comment]
I ran the following commond from the doc:

```pip install stata_kernel --ignore-install pexpect```

Got a highlighted line: 

```twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.```

I ingored it and contiuned the installation step it works in Atom. Btw, should I still install twisted and pyhamcrest?

**Comment by stevencollinscn** [comment]
Just got a error in Atom. Is this related?

```[IPKernelApp] ERROR | Exception in message handler: Traceback (most recent call last): File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell handler(stream, idents, msg) File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request user_expressions, allow_stdin) File "C:\Users\liqia\Anaconda3\lib\site-packages\stata_kernel\kernel.py", line 60, in do_execute text_to_run, md5, text_to_exclude=text_to_exclude) File "C:\Users\liqia\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 185, in do rc, res = self.expect(text=text, child=child, md5=md5, **kwargs) File "C:\Users\liqia\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 244, in expect self.kernel.send_image(child.match.group(1)) File "C:\Users\liqia\Anaconda3\lib\site-packages\stata_kernel\kernel.py", line 116, in send_image img = f.read() File "C:\Users\liqia\Anaconda3\lib\encodings\cp1252.py", line 23, in decode return codecs.charmap_decode(input,self.errors,decoding_table)[0] UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5801: character maps to```

**Comment by kylebarron** [comment]
I'm not completely sure what the issue is here. It could be an issue with `pip` itself, but I don't know. It should be working fine after the `--ignore-installed pexpect`...?

**Comment by stevencollinscn** [comment]
I pip installed `PyHamcrest`, and also tried pip install `twisted `, and got the following:
```
C:\Users\liqia>pip install twisted
Requirement already satisfied: twisted in c:\users\liqia\anaconda3\lib\site-packages (18.7.0)
Requirement already satisfied: zope.interface>=4.4.2 in c:\users\liqia\anaconda3\lib\site-packages (from twisted) (4.5.0)
Requirement already satisfied: constantly>=15.1 in c:\users\liqia\anaconda3\lib\site-packages (from twisted) (15.1.0)
Requirement already satisfied: incremental>=16.10.1 in c:\users\liqia\anaconda3\lib\site-packages (from twisted) (17.5.0)
Requirement already satisfied: Automat>=0.3.0 in c:\users\liqia\anaconda3\lib\site-packages (from twisted) (0.7.0)
Requirement already satisfied: hyperlink>=17.1.1 in c:\users\liqia\anaconda3\lib\site-packages (from twisted) (18.0.0)
Requirement already satisfied: PyHamcrest>=1.9.0 in c:\users\liqia\anaconda3\lib\site-packages (from twisted) (1.9.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\liqia\anaconda3\lib\site-packages (from twisted) (18.1.0)
Requirement already satisfied: setuptools in c:\users\liqia\anaconda3\lib\site-packages (from zope.interface>=4.4.2->twisted) (40.2.0)
Requirement already satisfied: six in c:\users\liqia\anaconda3\lib\site-packages (from Automat>=0.3.0->twisted) (1.11.0)
Requirement already satisfied: idna>=2.5 in c:\users\liqia\anaconda3\lib\site-packages (from hyperlink>=17.1.1->twisted) (2.7)
```
So, I guess it's fine.

**Comment by stevencollinscn** [comment]
@kylebarron I ran into the same issue while trying to pip upgrade the package. What should I do? 

```
C:\Users\liqia>pip install stata_kernel --upgrade
Collecting stata_kernel
  Downloading https://files.pythonhosted.org/packages/1e/49/eebc92f1a61570d4a7cdcabb16893e135f728b8202c30b6e1b359c654610/stata_kernel-1.4.7-py3-none-any.whl
Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.6.3 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (4.6.3)
Requirement already satisfied, skipping upgrade: pandas>=0.23.4 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (0.23.4)
Requirement already satisfied, skipping upgrade: pexpect>=4.6.0 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (4.6.0)
Requirement already satisfied, skipping upgrade: pygments>=2.2.0 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (2.2.0)
Requirement already satisfied, skipping upgrade: jupyter-client>=5.2.3 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (5.2.3)
Requirement already satisfied, skipping upgrade: regex>=2018.7.11 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (2018.8.29)
Requirement already satisfied, skipping upgrade: ipykernel>=4.8.2 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (4.9.0)
Requirement already satisfied, skipping upgrade: pillow>=5.2.0 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (5.2.0)
Requirement already satisfied, skipping upgrade: IPython>=6.5.0 in c:\users\liqia\anaconda3\lib\site-packages (from stata_kernel) (6.5.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.5.0 in c:\users\liqia\anaconda3\lib\site-packages (from pandas>=0.23.4->stata_kernel) (2.7.3)
Requirement already satisfied, skipping upgrade: pytz>=2011k in c:\users\liqia\anaconda3\lib\site-packages (from pandas>=0.23.4->stata_kernel) (2018.5)
Requirement already satisfied, skipping upgrade: numpy>=1.9.0 in c:\users\liqia\anaconda3\lib\site-packages (from pandas>=0.23.4->stata_kernel) (1.15.1)
Requirement already satisfied, skipping upgrade: ptyprocess>=0.5 in c:\users\liqia\anaconda3\lib\site-packages (from pexpect>=4.6.0->stata_kernel) (0.6.0)
Requirement already satisfied, skipping upgrade: traitlets in c:\users\liqia\anaconda3\lib\site-packages (from jupyter-client>=5.2.3->stata_kernel) (4.3.2)
Requirement already satisfied, skipping upgrade: jupyter_core in c:\users\liqia\anaconda3\lib\site-packages (from jupyter-client>=5.2.3->stata_kernel) (4.4.0)
Exception:
Traceback (most recent call last):
  File "c:\users\liqia\anaconda3\lib\site-packages\pip\_internal\basecommand.py", line 141, in main
    status = self.run(options, args)
  File "c:\users\liqia\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "c:\users\liqia\anaconda3\lib\site-packages\pip\_internal\resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\users\liqia\anaconda3\lib\site-packages\pip\_internal\resolve.py", line 261, in _resolve_one
    check_dist_requires_python(dist)
  File "c:\users\liqia\anaconda3\lib\site-packages\pip\_internal\utils\packaging.py", line 46, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "c:\users\liqia\anaconda3\lib\email\feedparser.py", line 175, in feed
    self._input.push(data)
  File "c:\users\liqia\anaconda3\lib\email\feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'
```

**Comment by kylebarron** [comment]
Did you try `pip install stata_kernel --ignore-install pexpect`?

**Comment by stevencollinscn** [comment]
So I just need to overwrite the package for the update? I don't understand why it raises an exception. Btw, is there any way I can know whether I need to upgrade the kernel or not?

**Comment by kylebarron** [comment]
Ok. Did `pip install stata_kernel --ignore-install pexpect` work?

**Comment by stevencollinscn** [comment]
Yes, `stata-kernel-1.4.7` is installed. I wonder if this will also upgrade `numpy`, `pandas`, etc. every time when I upgrade `stata_kernel`. I wonder if there is a way to upgrade it only.

**Comment by kylebarron** [comment]
You can google but I think you could do `pip install stata-kernel==1.4.7` and that would upgrade `stata_kernel` without upgrading anything else.
