### ISSUE TITLE
Kernel updates but then crashes

### ISSUE THREAD

**Issue by hugobaltasar** [kylebarron/stata_kernel#148]
#### Problem description

I am not sure if this is the correct place to post this, excuses in advance if it's not. I have installed the kernel following your instructions at [stata_kernel](https://kylebarron.github.io/stata_kernel/), but setting up a virtual env, like this:

```
python3 -m venv env
source ./env/bin/activate
pip install stata_kernel
```

However, when I try to run it I get the following (long) error message, either in Atom or Jupyter console:

```
Traceback (most recent call last):
  File "/home/hugomv/env/lib/python3.6/site-packages/pexpect/spawnbase.py", line 166, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hugomv/env/lib/python3.6/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/home/hugomv/env/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/home/hugomv/env/lib/python3.6/site-packages/pexpect/spawnbase.py", line 171, in read_nonblocking
    raise EOF('End Of File (EOF). Exception style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hugomv/env/lib/python3.6/site-packages/stata_kernel/__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "/home/hugomv/env/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/home/hugomv/env/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/hugomv/env/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 476, in initialize
    self.init_kernel()
  File "/home/hugomv/env/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 387, in init_kernel
    user_ns=self.user_ns,
  File "/home/hugomv/env/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/home/hugomv/env/lib/python3.6/site-packages/stata_kernel/kernel.py", line 36, in __init__
    self.stata = StataSession(self, self.conf)
  File "/home/hugomv/env/lib/python3.6/site-packages/stata_kernel/stata_session.py", line 55, in __init__
    self.init_console()
  File "/home/hugomv/env/lib/python3.6/site-packages/stata_kernel/stata_session.py", line 118, in init_console
    self.child.expect('\r\n\. ', timeout=0.2)
  File "/home/hugomv/env/lib/python3.6/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/home/hugomv/env/lib/python3.6/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/home/hugomv/env/lib/python3.6/site-packages/pexpect/expect.py", line 117, in expect_loop
    return self.eof(e)
  File "/home/hugomv/env/lib/python3.6/site-packages/pexpect/expect.py", line 63, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7f661ca958d0>
command: /usr/local/stata14/xstata-mp
args: [b'/usr/local/stata14/xstata-mp']
buffer (last 100 chars): ''

after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 9198
child_fd: 50
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <_io.TextIOWrapper name='/home/hugomv/.stata_kernel_cache/console_debug.log' mode='w' encoding='UTF-8'>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: None
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('\r\n\\. ')

Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-116>", line 2, in initialize
  File "/usr/local/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_console/app.py", line 141, in initialize
    self.init_shell()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_console/app.py", line 114, in init_shell
    client=self.kernel_client,
  File "/usr/local/anaconda3/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 272, in __init__
    self.init_kernel_info()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 323, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_client/client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 50, in get_msg
    ready = self.socket.poll(timeout)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py", line 695, in poll
    evts = dict(p.poll(timeout))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 143, in zmq.backend.cython._poll.zmq_poll
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_console/app.py", line 123, in handle_sigint
    if self.shell._executing:
AttributeError: 'ZMQTerminalIPythonApp' object has no attribute 'shell'
```

Or course, the kernel does not work. I had no problems with Hydrogen, and R, Python and Julia kernels work properly. In fact, if I run `jupyter kernelspec list` I get the following:

```
Available kernels:
  ir           /home/hugomv/.local/share/jupyter/kernels/ir
  julia-0.6    /home/hugomv/.local/share/jupyter/kernels/julia-0.6
  stata        /home/hugomv/.local/share/jupyter/kernels/stata
  python3      /usr/local/anaconda3/share/jupyter/kernels/python3
```

Also, if I run `sudo jupyter console --kernel stata`, the error message is considerably shorter, but it doesn't work anyway:

```
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-116>", line 2, in initialize
  File "/usr/local/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_console/app.py", line 141, in initialize
    self.init_shell()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_console/app.py", line 109, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_client/consoleapp.py", line 334, in initialize
    self.init_kernel_manager()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_client/consoleapp.py", line 288, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 246, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 236, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named stata
```

#### Debugging log

The debugging log is empty.

#### Other information

- Operating System: Manjaro Linux GNOME 17.1.12
- Stata version: 14.2 64-bit x86-64
- Package version: 1.4.5

**Comment by kylebarron** [comment]
Can you do `pip show jupyter_client` within your venv?

**Comment by kylebarron** [comment]
Actually this might be it:
```
command: /usr/local/stata14/xstata-mp
```

`xstata-mp` is the GUI version of Stata. Try changing this to `/usr/local/stata14/stata-mp`.

**Comment by hugobaltasar** [comment]
Thanks for such a fast answer!

Once I changed `/usr/local/stata14/xstata-mp` for `/usr/local/stata14/stata-mp` the error message is basically the same, with minor changes.

When I write `pip show jupyter_client` in my env I get:

```
Name: jupyter-client
Version: 5.2.3
Summary: Jupyter protocol implementation and client libraries
Home-page: https://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /home/hugomv/env/lib/python3.6/site-packages
Requires: pyzmq, traitlets, python-dateutil, jupyter-core, tornado
Required-by: stata-kernel, ipykernel
```

**Comment by kylebarron** [comment]
1. You shouldn't be (and shouldn't need to be) running it with `sudo`
2. It seems that it isn't reaching the initial dot prompt within Stata. From the normal `stata-mp` console, can you try `set more off, permanently`, and then try starting the kernel again?

**Comment by hugobaltasar** [comment]
You were right, it wasn't reaching it. The first problem was that I had set the path to the GUI version, the second that the `stata-mp` console itself wasn't working (although the GUI version was).

I'll write what solved the case for me here in case someone faces the same issue: seems to be that Stata (my version at least) needs `libncurses.so.5`, and I have `libncurses.so.6.1` installed, so I had to create a symbolic link following [this answer in stackoverflow](https://stackoverflow.com/a/42686791/7813935). That solved my problem and now the kernel it's working like a charm. 

Thank you for such an outstanding assistance pointing me in the right direction! Closing the issue now.

**Comment by kylebarron** [comment]
Setting the GUI version would be pretty common among users, so I should account for that.

ncurses can be an annoying dependency. I hadn't seen a linux user with the wrong ncurses version before, so I'm guessing it might be particular to your Linux distro.
