### ISSUE TITLE
EOF issues on Windows

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#192]
Might be ideal to try to create a pipe like this SO answer: https://stackoverflow.com/a/25770830. Otherwise need to change `maxread` or maybe account for `EOF` in that `expect`...

From https://github.com/jhconning/Dev-II/issues/1#issuecomment-423047177:

> Argh, you are right, both jupyter lab and notebook are not displaying on my Win10 machine. Graphics were working on my Win 7 machine at work.
> 
> The following is sent to the jupyter server log in terminal window (excerpt):
> 
> ```
> [IPKernelApp] ERROR | Exception in message handler:
> Traceback (most recent call last):
>   File "C:\Users\jconning\AppData\Local\Continuum\Anaconda3\lib\site-packages\pexpect\expect.py", line 111, in expect_loop
>     incoming = spawn.read_nonblocking(spawn.maxread, timeout)
>   File "C:\Users\jconning\AppData\Local\Continuum\Anaconda3\lib\site-packages\pexpect\fdpexpect.py", line 148, in read_nonblocking
>     return super(fdspawn, self).read_nonblocking(size)
>   File "C:\Users\jconning\AppData\Local\Continuum\Anaconda3\lib\site-packages\pexpect\spawnbase.py", line 176, in read_nonblocking
>     raise EOF('End Of File (EOF). Empty string style platform.')
> pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\jconning\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
>     handler(stream, idents, msg)
>   File "C:\Users\jconning\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
>     user_expressions, allow_stdin)
>   File "C:\Users\jconning\AppData\Local\Continuum\Anaconda3\lib\site-packages\stata_kernel\kernel.py", line 109, in do_execute
>     text_to_run, md5, text_to_exclude=text_to_exclude)
>   File "C:\Users\jconning\AppData\Local\Continuum\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 217, in do
>     rc, res = self.expect(text=text, child=child, md5=md5, **kwargs)
>   File "C:\Users\jconning\AppData\Local\Continuum\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 282, in expect
>     child.expect(g_exp, timeout=None)
>   File "C:\Users\jconning\AppData\Local\Continuum\Anaconda3\lib\site-packages\pexpect\spawnbase.py", line 341, in expect
>     timeout, searchwindowsize, async_)
>   File "C:\Users\jconning\AppData\Local\Continuum\Anaconda3\lib\site-packages\pexpect\spawnbase.py", line 369, in expect_list
>     return exp.expect_loop(timeout)
>   File "C:\Users\jconning\AppData\Local\Continuum\Anaconda3\lib\site-packages\pexpect\expect.py", line 117, in expect_loop
>     return self.eof(e)
>   File "C:\Users\jconning\AppData\Local\Continuum\Anaconda3\lib\site-packages\pexpect\expect.py", line 63, in eof
>     raise EOF(msg)
> pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.
> <pexpect.fdpexpect.fdspawn object at 0x0000024FA6DE7E48>
> searcher: searcher_re:
>     0: re.compile('\\(file (C:/Users/jconning/.stata_kernel_cache/graph\\d+\\.(svg|png|pdf)) written in (?i:(svg|png|pdf)) format\\)')
> ```

**Comment by kylebarron** [comment]
Specifically this line doesn't catch `expect.EOF`:
https://github.com/kylebarron/stata_kernel/blob/e94495740d239fcf515955ad44cae22ca02e2fb7/stata_kernel/stata_session.py#L283

**Comment by kylebarron** [comment]
Just try to encapsulate that in a `while match_index != 0`, and sleep for 0.05s after EOF
