### ISSUE TITLE
Message showing how long each command takes to execute throws an error

### ISSUE THREAD

**Issue by hugobaltasar** [kylebarron/stata_kernel#199]
#### Problem description

If one runs `set rmsg on` the kernel shows an error message thereafter every time a command is run, i.e., every time it must show the time it took to complete the last command and the exact time when it was completed. Please note that the time message is indeed shown (although with a little variation from what Stata does: the kernel shows not only the time when the last command finished executing, but also when did so the next-to-last one), it simply adds an error message that does not seem to affect the expected behavior. 

In my case, the error message is:

```
[IPKernelApp] ERROR | Exception in message handler: Traceback (most recent call last): 
File "/home/hugoea/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell handler(stream, idents, msg) 
File "/home/hugoea/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request user_expressions, allow_stdin) 
File "/home/hugoea/anaconda3/lib/python3.6/site-packages/stata_kernel/kernel.py", line 113, in do_execute self.post_do_hook() 
File "/home/hugoea/anaconda3/lib/python3.6/site-packages/stata_kernel/kernel.py", line 144, in post_do_hook self.stata.linesize = int(res.strip()) 
ValueError: invalid literal for int() with base 10: 'r; t=0.00 19:02:19\n255\nr; t=0.00 19:02:19'
```

It is not a serious problem of course, but can be annoying. Having the possibility of setting rmsg on can be a nice improvement.

I take the chance to thank you for this awesome tool!

#### Other information

- elementary OS 0.4.1 Loki (64-bit)
- 14.2MP
- 1.5.5

**Comment by kylebarron** [comment]
Should be fixed with https://github.com/kylebarron/stata_kernel/commit/30e33003ca5686ff48c55fa340b0ab211316bf78. Try after upgrading.

There are sometimes extra `rmsg` messages shown, i.e. with graphs. Ideally I'd reimplement the `%time` magic, but I don't have time to code that at the moment.

**Comment by hugobaltasar** [comment]
I can confirm the fix works in my system. Thanks!
