### ISSUE TITLE
"bad escape" error

### ISSUE THREAD

**Issue by phross** [kylebarron/stata_kernel#201]
I'm trying to run the Stata kernel using Anaconda 3, python 3.7 and jupyter notebook in Windows 10. I'm encountering the following errors in getting the kernel running. Any suggestions?
```
KeyError: '\\s'
```
and
```
 File "C:\Users\phill\Anaconda3\lib\sre_parse.py", line 1024, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \s at position 0
```
Here is the entirety of the output:
```

(base) C:\Users\phill>jupyter console --kernel stata
Traceback (most recent call last):
  File "C:\Users\phill\Anaconda3\lib\sre_parse.py", line 1021, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\s'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\phill\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\phill\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\phill\Anaconda3\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\phill\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\phill\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\phill\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 478, in initialize
    self.init_kernel()
  File "C:\Users\phill\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\phill\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\phill\Anaconda3\lib\site-packages\stata_kernel\kernel.py", line 73, in __init__
    self.completions = CompletionsManager(self, self.conf)
  File "C:\Users\phill\Anaconda3\lib\site-packages\stata_kernel\completions.py", line 69, in __init__
    self.suggestions = self.get_suggestions(kernel)
  File "C:\Users\phill\Anaconda3\lib\site-packages\stata_kernel\completions.py", line 266, in get_suggestions
    match = self.matchall(self.quickdo('_StataKernelCompletions', kernel))
  File "C:\Users\phill\Anaconda3\lib\site-packages\stata_kernel\completions.py", line 297, in quickdo
    text_to_run, md5, text_to_exclude = cm.get_text(kernel.conf)
  File "C:\Users\phill\Anaconda3\lib\site-packages\stata_kernel\code_manager.py", line 261, in get_text
    for x in user_graph_keywords.split(',')]
  File "C:\Users\phill\Anaconda3\lib\site-packages\stata_kernel\code_manager.py", line 261, in <listcomp>
    for x in user_graph_keywords.split(',')]
  File "C:\Users\phill\Anaconda3\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\phill\Anaconda3\lib\re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Users\phill\Anaconda3\lib\re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\phill\Anaconda3\lib\sre_parse.py", line 1024, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \s at position 0
```

**Comment by kylebarron** [comment]
Do you know what version of the package you're running? (You can find this out with `pip show stata_kernel`). Are you able to run any code?

**Comment by phross** [comment]
I'm running 1.5.6
```
C:\Users\phill>pip show stata_kernel
Name: stata-kernel
Version: 1.5.6
Summary: A Jupyter kernel for Stata. Works with Windows, macOS, and Linux. Preserves program state.
Home-page: https://github.com/kylebarron/stata_kernel
Author: Kyle Barron
Author-email: barronk@mit.edu
License: GPLv3
Location: c:\users\phill\anaconda3\lib\site-packages
Requires: requests, jupyter-client, pywin32, regex, beautifulsoup4, pygments, jupyter, pandas, packaging, pillow, pexpect, IPython, ipykernel
Required-by:
```

**Comment by kylebarron** [comment]
If you have git installed, you could try
```
pip install git+https://github.com/kylebarron/stata_kernel@dev-issue-201 --upgrade
```
and see if that fixes it?

**Comment by kylebarron** [comment]
The new release should be on `pip` for standard `pip install stata_kernel --upgrade` installation.

**Comment by anilpankaj** [comment]
Traceback (most recent call last):
  File "dialogue_management_model.py", line 55, in <module>
    run_weather_bot()
  File "dialogue_management_model.py", line 46, in run_weather_bot
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/current')
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 234, in __init__
    self._load_interpreter()
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 257, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 304, in load
    skip_validation)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 331, in create
    model_metadata, **context)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_nlu/components.py", line 425, in load_component
    cached_component, **context)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_nlu/registry.py", line 172, in load_component_by_meta
    cached_component, **kwargs)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_nlu/utils/spacy_utils.py", line 114, in load
    nlp = spacy.load(model_name, disable=['parser'])
  File "/home/anil/.local/lib/python3.6/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/anil/.local/lib/python3.6/site-packages/spacy/util.py", line 129, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/anil/.local/lib/python3.6/site-packages/spacy/util.py", line 146, in load_model_from_link
    return cls.load(**overrides)
  File "/home/anil/.local/lib/python3.6/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/anil/.local/lib/python3.6/site-packages/spacy/util.py", line 190, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/anil/.local/lib/python3.6/site-packages/spacy/util.py", line 173, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/anil/.local/lib/python3.6/site-packages/spacy/language.py", line 791, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/anil/.local/lib/python3.6/site-packages/spacy/util.py", line 630, in from_disk
    reader(path / key)
  File "/home/anil/.local/lib/python3.6/site-packages/spacy/language.py", line 781, in <lambda>
    deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(p, exclude=["vocab"])
  File "tokenizer.pyx", line 391, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 437, in spacy.tokenizer.Tokenizer.from_bytes
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 527, in _parse
    code1 = _class_escape(source, this)
  File "/usr/lib/python3.6/sre_parse.py", line 336, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
sre_constants.error: bad escape \p at position 257
when i run this code that's i mention below i got that error so please help!

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging
import re
import warnings
import ruamel.yaml
warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

from rasa_core.agent import Agent
from rasa_core.policies import FallbackPolicy, KerasPolicy, MemoizationPolicy
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.training import interactive
from rasa_core.utils import EndpointConfig

logger = logging.getLogger(__name__)


# this will catch predictions the model isn't very certain about
# there is a threshold for the NLU predictions as well as the action predictions
fallback = FallbackPolicy(fallback_action_name="utter_unclear",
                          core_threshold=0.2,
                          nlu_threshold=0.1)

def train_dialogue(interpreter,domain_file = 'domain.yml',
                   model_path = './models/dialogue',
                   training_data_file = './data/stories.md'):

    #action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
    agent = Agent(domain_file, policies=[MemoizationPolicy(), KerasPolicy(), fallback])
    training_data = agent.load_data('./data/stories.md')

    agent.train(
            training_data)

    agent.persist('models/dialogue')
    return agent




def run_weather_bot(serve_forever=True):
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/current')
    action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
    agent = Agent.load('./models/dialogue', interpreter=nlu_interpreter, action_endpoint=action_endpoint)
    #rasa_core.run.serve_application(agent ,channel='cmdline')
    
    return agent

if __name__ == '__main__':
    train_dialogue(interpreter=RasaNLUInterpreter)
    run_weather_bot()
