### ISSUE TITLE
Starting Kernel on Windows10 Causes Errors and Loads Multiple (GUIs)

### ISSUE THREAD

**Issue by adamrossnelson** [kylebarron/stata_kernel#225]
#### Problem description

Thanks for the great work on this. I've used it on Mac, Windows, and Linux. All without bugs. Today I went to start a notebook with the Stata Kernel. The current setting worked fine last week. Here is a description of the behavior today:

1 . Launch Jupyter Notebook.
2. Open a new notebook with the Stata Kernel.
3. Immediately launching the Stata Kernel I get five GUI sessions of Stata in my start bar.
4. Below is the output from my Anaconda Prompt window.

It was a long while ago, but when I last successfully ran a Stata Kernel on a Windows computer I don't recall the GUI also launching (certainly not five times). Looks like maybe my configuration has a flaw which is bypassing the Windows Stata Automation which causes an error and then it tries again four more times.

#### Debugging log

My installation is not producing a log file at: `$HOME/.stata_kernel_cache/console_debug.log` which on this setup is `D:\Users\data_science_role\.stata_kernel_cache`.

_From my Anaconda Prompt window:_

```
[I 10:13:11.979 NotebookApp] Creating new notebook in /confdata
[I 10:13:13.082 NotebookApp] Kernel started: b5d37a6b-2dc3-447a-8772-7224e065c6a1
Traceback (most recent call last):
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 478, in initialize
    self.init_kernel()
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\kernel.py", line 69, in __init__
    self.stata = StataSession(self, self.conf)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 66, in __init__
    self.init_windows()
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 109, in init_windows
    self.stata = win32com.client.Dispatch("stata.StataOLEApp")
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)
[I 10:13:16.083 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 478, in initialize
    self.init_kernel()
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\kernel.py", line 69, in __init__
    self.stata = StataSession(self, self.conf)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 66, in __init__
    self.init_windows()
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 109, in init_windows
    self.stata = win32com.client.Dispatch("stata.StataOLEApp")
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)
[I 10:13:19.096 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 478, in initialize
    self.init_kernel()
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\kernel.py", line 69, in __init__
    self.stata = StataSession(self, self.conf)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 66, in __init__
    self.init_windows()
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 109, in init_windows
    self.stata = win32com.client.Dispatch("stata.StataOLEApp")
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)
[I 10:13:22.093 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 478, in initialize
    self.init_kernel()
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\kernel.py", line 69, in __init__
    self.stata = StataSession(self, self.conf)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 66, in __init__
    self.init_windows()
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 109, in init_windows
    self.stata = win32com.client.Dispatch("stata.StataOLEApp")
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)
[I 10:13:25.099 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 478, in initialize
    self.init_kernel()
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\kernel.py", line 69, in __init__
    self.stata = StataSession(self, self.conf)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 66, in __init__
    self.init_windows()
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 109, in init_windows
    self.stata = win32com.client.Dispatch("stata.StataOLEApp")
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "D:\Users\data_science_role\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)
[W 10:13:28.110 NotebookApp] KernelRestarter: restart failed
[W 10:13:28.110 NotebookApp] Kernel b5d37a6b-2dc3-447a-8772-7224e065c6a1 died, removing from map.
[W 10:14:13.114 NotebookApp] Timeout waiting for kernel_info reply from b5d37a6b-2dc3-447a-8772-7224e065c6a1
[E 10:14:46.549 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: b5d37a6b-2dc3-447a-8772-7224e065c6a1)
```

#### Code Sample

Not applicable

#### Expected Output

Not applicable

#### Other information

If you didn't attach the debugging log, please provide:

- OS Name:	Microsoft Windows [Version 10.0.14393]
- Stata Version / Location: C:\Program Files (x86)\Stata15\StataSE-64.exe
- Package information:

```
Name: stata-kernel
Version: 1.6.2
Summary: A Jupyter kernel for Stata. Works with Windows, macOS, and Linux. Preserves program state.
Home-page: https://github.com/kylebarron/stata_kernel
Author: Kyle Barron
Author-email: barronk@mit.edu
License: GPLv3
Location: d:\users\data_science_role\appdata\local\continuum\anaconda3\lib\site-packages
Requires: pygments, pandas, pexpect, jupyter-client, requests, ipykernel, beautifulsoup4, IPython, packaging, pillow, jupyt
er, pywin32
Required-by:
```
Also useful to know:

- Stata runs on its own fine.
- Python Kernel running fine.

#### Other steps taken

1. Ran `pip install stata_kernel --upgrade`
2. Restarted computer.
3. Restarted Jupyter Notebooks.
4. Started new notebook with Stata Kernel.
5. Error seems to be persisting.

After the above:

1. Started Jupyter Notebooks in Firefox instead of Chrome.
2. Error persists in Firefox.

After the above:

1. Uninstalled Stata
2. Installed Stata
3. Restarted computer
4. Ran `pip install stata_kernel --upgrade`
5. Started new notebook with Stata Kernel.
6. Error seems to be persisting.

#### Edit(s):

Oct 29 11am Eastern Time: Added explanatory text in italics under debug log.

**Comment by kylebarron** [comment]
This means your Stata Automation type library isn't registered. Following [these steps](https://kylebarron.github.io/stata_kernel/getting_started/#prerequisites) will fix it.

**Comment by kylebarron** [comment]
Basically it first launches a Stata GUI session separately and then tries to connect to that session with Stata automation. When it can't, the program crashes. Jupyter tries to restart the kernel 5 times by default, so it creates 5 separate Stata windows without being able to connect to any of them.

**Comment by adamrossnelson** [comment]
Yes! That is it.

So sorry for overlooking that. In the process of implementing the "Windows Specific Steps" I recall having done that on a previous instance. So thankful for your quick response. Thanks again for the great work.

Hopefully perhaps this issue in the thread will help others.

Closing issue. Thanks.
