### ISSUE TITLE
Kernel won't start with rmsg on

### ISSUE THREAD

**Issue by vargac10** [kylebarron/stata_kernel#263]
#### Problem description
I've install Anaconda and used Anaconda prompt to input the package install code from your [page](https://kylebarron.github.io/stata_kernel/getting_started/#using). However, when I launch Notebooks from Anaconda Navigator and select Stata notebook. It starts the new window, but the kernel does not start up. It repeated opens and closes a Stata window. After a while, it opens a prompt saying that "The kernel appears to have died."

I have tried  ` pip install stata_kernel --upgrade` but that did not help.

#### Other information

If you didn't attach the debugging log, please provide:

- Windows 7
- Stata version 15.1
- Package version 1.8.0

**Comment by kylebarron** [comment]
> It repeated opens and closes a Stata window. After a while, it opens a prompt saying that "The kernel appears to have died."

The most likely issue is that you need to register the type library. See [here](https://kylebarron.github.io/stata_kernel/getting_started/#prerequisites) under "Windows specific steps".

**Comment by vargac10** [comment]
I've tried that but it didn't work out. I still have the busy status on notebooks and Stata window flashing.

**Comment by vargac10** [comment]
Yes.

**Comment by vargac10** [comment]
Right now, even though no notebooks are open. Stata window still continues to flash open and close.

**Comment by kylebarron** [comment]
It doesn't seem to be a core issue with Stata Kernel. I think when you installed Anaconda, you checked "Install for all users" instead of "install for just me". That looks like it created a permissions problem for Jupyter. 

Try this:
1. Uninstall Anaconda. Run the program at `C:\ProgramData\Ana
conda3\Uninstall-Anaconda3.exe`.
2. Install Anaconda again, checking "Install for just me" on the install screen.
3. Install `stata_kernel` again

**Comment by vargac10** [comment]
I have uninstalled Anaconda, and reinstalled with "Install for just me". And re-installed `stata_kernel`. But the issue remains.

**Comment by kylebarron** [comment]
Are you able to open a Python notebook now?

**Comment by vargac10** [comment]
`[I 14:47:09.250 NotebookApp] The port 8888 is already in use, trying another por
t.
[I 14:47:09.251 NotebookApp] The port 8889 is already in use, trying another por
t.
[I 14:47:09.345 NotebookApp] JupyterLab extension loaded from C:\Users\vargac10\
AppData\Local\Continuum\anaconda3\lib\site-packages\jupyterlab
[I 14:47:09.345 NotebookApp] JupyterLab application directory is C:\Users\vargac
10\AppData\Local\Continuum\anaconda3\share\jupyter\lab
[I 14:47:09.353 NotebookApp] Serving notebooks from local directory: C:\Users\va
rgac10
[I 14:47:09.354 NotebookApp] The Jupyter Notebook is running at:
[I 14:47:09.354 NotebookApp] http://localhost:8890/?token=145c3718479b799f99d9b5
fd36eda3e9591c7879b95e6bf4
[I 14:47:09.354 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
[C 14:47:09.491 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8890/?token=145c3718479b799f99d9b5fd36eda3e9591c7879b95
e6bf4
[I 14:47:09.985 NotebookApp] Accepting one-time-token-authenticated connection f
rom ::1
[I 14:47:16.335 NotebookApp] Kernel started: b8989ebd-8607-4aee-ab06-6feacd0c484
f
[I 14:47:18.543 NotebookApp] Adapting to protocol v5.1 for kernel b8989ebd-8607-
4aee-ab06-6feacd0c484f
[I 14:47:34.119 NotebookApp] Kernel started: 29702922-fbb4-4f17-b6ef-1a88e5cd02e
9
[I 14:47:35.937 NotebookApp] Adapting to protocol v5.1 for kernel 29702922-fbb4-
4f17-b6ef-1a88e5cd02e9
[I 14:47:37.047 NotebookApp] Starting buffering for 29702922-fbb4-4f17-b6ef-1a88
e5cd02e9:8ba3bad9e41348a1862736c8add836b6
[I 14:47:40.137 NotebookApp] Starting buffering for b8989ebd-8607-4aee-ab06-6fea
cd0c484f:a555517cc4ab48f68910cad94b38e545
[I 14:47:45.628 NotebookApp] Kernel shutdown: b8989ebd-8607-4aee-ab06-6feacd0c48
4f
[W 14:47:45.635 NotebookApp] delete /Untitled2.ipynb
[W 14:47:45.672 NotebookApp] delete /Untitled1.ipynb
[W 14:47:45.684 NotebookApp] delete /Untitled.ipynb
[I 14:47:47.925 NotebookApp] Creating new notebook in
[I 14:47:50.062 NotebookApp] Kernel started: b51b7b31-01eb-4936-9bb1-41ca625e3df
c
Traceback (most recent call last):
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\runpy.py", line
193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\runpy.py", line
85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\ip
ykernel\kernelapp.py", line 478, in initialize
    self.init_kernel()
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\ip
ykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\kernel.py", line 71, in __init__
    self.stata = StataSession(self, self.conf)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\stata_session.py", line 131, in __init__
    isold = int(self.stata_version[:2]) < 15
ValueError: invalid literal for int() with base 10: 'r;'
[I 14:47:56.037 NotebookApp] KernelRestarter: restarting kernel (1/5), keep rand
om ports
Traceback (most recent call last):
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\runpy.py", line
193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\runpy.py", line
85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\ip
ykernel\kernelapp.py", line 478, in initialize
    self.init_kernel()
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\ip
ykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\kernel.py", line 71, in __init__
    self.stata = StataSession(self, self.conf)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\stata_session.py", line 131, in __init__
    isold = int(self.stata_version[:2]) < 15
ValueError: invalid literal for int() with base 10: 'r;'
[I 14:48:05.054 NotebookApp] KernelRestarter: restarting kernel (1/5), keep rand
om ports
Traceback (most recent call last):
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\runpy.py", line
193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\runpy.py", line
85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\ip
ykernel\kernelapp.py", line 478, in initialize
    self.init_kernel()
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\ip
ykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\kernel.py", line 71, in __init__
    self.stata = StataSession(self, self.conf)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\stata_session.py", line 131, in __init__
    isold = int(self.stata_version[:2]) < 15
ValueError: invalid literal for int() with base 10: 'r;'
[I 14:48:14.060 NotebookApp] KernelRestarter: restarting kernel (1/5), keep rand
om ports
Traceback (most recent call last):
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\runpy.py", line
193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\runpy.py", line
85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\ip
ykernel\kernelapp.py", line 478, in initialize
    self.init_kernel()
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\ip
ykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\kernel.py", line 71, in __init__
    self.stata = StataSession(self, self.conf)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\stata_session.py", line 131, in __init__
    isold = int(self.stata_version[:2]) < 15
ValueError: invalid literal for int() with base 10: 'r;'
[I 14:48:23.075 NotebookApp] KernelRestarter: restarting kernel (1/5), keep rand
om ports
[I 14:48:26.880 NotebookApp] Kernel interrupted: b51b7b31-01eb-4936-9bb1-41ca625
e3dfc
Traceback (most recent call last):
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\runpy.py", line
193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\runpy.py", line
85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\ip
ykernel\kernelapp.py", line 478, in initialize
    self.init_kernel()
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\ip
ykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\kernel.py", line 71, in __init__
    self.stata = StataSession(self, self.conf)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\stata_session.py", line 131, in __init__
    isold = int(self.stata_version[:2]) < 15
ValueError: invalid literal for int() with base 10: 'r;'
[I 14:48:32.091 NotebookApp] KernelRestarter: restarting kernel (1/5), keep rand
om ports
Traceback (most recent call last):
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\runpy.py", line
193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\runpy.py", line
85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\ip
ykernel\kernelapp.py", line 478, in initialize
    self.init_kernel()
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\ip
ykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\tr
aitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\kernel.py", line 71, in __init__
    self.stata = StataSession(self, self.conf)
  File "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\lib\site-packages\st
ata_kernel\stata_session.py", line 131, in __init__
    isold = int(self.stata_version[:2]) < 15
ValueError: invalid literal for int() with base 10: 'r;'
[I 14:48:41.090 NotebookApp] KernelRestarter: restarting kernel (1/5), keep rand
om ports
[I 14:48:47.089 NotebookApp] Kernel shutdown: b51b7b31-01eb-4936-9bb1-41ca625e3d
fc
[W 14:48:50.093 NotebookApp] Timeout waiting for kernel_info reply from b51b7b31
-01eb-4936-9bb1-41ca625e3dfc
[E 14:48:50.098 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel d
oes not exist: b51b7b31-01eb-4936-9bb1-41ca625e3dfc)
[W 14:48:51.706 NotebookApp] delete /Untitled.ipynb
`

**Comment by vargac10** [comment]
python notebook works. but the stata kernel does not

**Comment by kylebarron** [comment]
Thanks. Now we got to the Stata kernel issue. Can you attach the file
```
C:\Users\vargac10\.stata_kernel_cache\console_debug.log
```

**Comment by vargac10** [comment]
`------------------------------------------------------------------------------------------------------------------------------------------------------------------------

      name:  stata_kernel_log

       log:  C:\Users\vargac10\.stata_kernel_cache\log0.log

  log type:  text

 opened on:  14 Dec 2018, 15:02:46

adopath + `"C:\Users\vargac10\AppData\Local\Continuum\anaconda3\Lib\site-packages\stata_kernel\ado"'

  [1]  (BASE)      "C:\Program Files (x86)\Stata15\ado\base/"

  [2]  (SITE)      "C:\Program Files (x86)\Stata15\ado\site/"

  [3]              "."

  [4]  (PERSONAL)  "c:\ado\personal/"

  [5]  (PLUS)      "c:\ado\plus/"

  [6]  (OLDPLACE)  "c:\ado/"

  [7]              "C:\Users\vargac10\AppData\Local\Continuum\anaconda3\Lib\site-packages\stata_kernel\ado"

r; t=0.01 15:02:46



. cd `"C:\Users\vargac10"'

C:\Users\vargac10

r; t=0.00 15:02:46



. set more on

r; t=0.00 15:02:46



. set pagesize 100

r; t=0.00 15:02:46



. set linesize 255

r; t=0.00 15:02:46



. clear all

r; t=0.02 15:02:46



. global stata_kernel_graph_counter = 0

r; t=0.00 15:02:46



. 

. di "$S_DATE, $S_TIME"

14 Dec 2018, 15:02:46

r; t=0.00 15:02:46



. di "Stata version: `c(version)'"

Stata version: 15

r; t=0.00 15:02:46



. di "OS: $S_OS"

OS: Windows

r; t=0.00 15:02:46



. `finished_init_cmd'

r; t=0.00 15:02:46

. di "`c(stata_version)'"

15

r; t=0.00 15:02:46



. `done'

r; t=0.00 15:02:46

`

**Comment by vargac10** [comment]
[console_debug.log](https://github.com/kylebarron/stata_kernel/files/2681583/console_debug.log)

**Comment by kylebarron** [comment]
The reason it's not working is because you have `rmsg` turned on permanently. In a separate Stata session, run
```stata
set rmsg off, permanently
```

This is still a bug that I should fix, but I think the above should be a short term solution for you.

**Comment by vargac10** [comment]
It worked! I turned rmsg off, permanently

Thanks!
