### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by DenzelGlandel** [kylebarron/stata_kernel#281]
#### Problem description

After installing stata kernel on Windows and registering the Stata Automation Library, jupyter notebook gives this error when starting a Stata Notebook:

    ```
    AttributeError: 'StataSession' object has no attribute 'stata'
    ```

**Comment by lordflaron** [comment]
Sorry continuing from here. 

Thank you for any help you can provide.

**Comment by kylebarron** [comment]
Can you post the full log file? It should be in %USERPROFILE%\.stata_kernel_cache\console.log or similar

**Comment by kylebarron** [comment]
Or probably more importantly, can you copy paste the full traceback. You only pasted the last line of the error message

**Comment by DenzelGlandel** [comment]
Sorry About that, currently at a talk and many people are having this problem

```

(base) C:\Users\denze\Documents\GitHub>jupyter notebook
[I 09:55:58.798 NotebookApp] JupyterLab extension loaded from C:\Users\denze\Anaconda3\lib\site-packages\jupyterlab
[I 09:55:58.798 NotebookApp] JupyterLab application directory is C:\Users\denze\Anaconda3\share\jupyter\lab
[I 09:55:58.813 NotebookApp] Serving notebooks from local directory: C:\Users\denze\Documents\GitHub
[I 09:55:58.813 NotebookApp] The Jupyter Notebook is running at:
[I 09:55:58.813 NotebookApp] http://localhost:8888/?token=5cb2ca738e73a4c15ac13e4eff07faeca67bb3f56acdedd2
[I 09:55:58.813 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:55:58.923 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/denze/AppData/Roaming/jupyter/runtime/nbserver-6592-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=5cb2ca738e73a4c15ac13e4eff07faeca67bb3f56acdedd2
[I 09:56:27.926 NotebookApp] Creating new notebook in
[I 09:56:31.025 NotebookApp] Kernel started: cf9805f9-9d45-4c8e-826e-d9ddbef955f1
Traceback (most recent call last):
  File "C:\Users\denze\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\denze\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\denze\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 484, in initialize
    self.init_kernel()
  File "C:\Users\denze\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\kernel.py", line 73, in __init__
    self.stata = StataSession(self, self.conf)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 86, in __init__
    self.init_windows()
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 159, in init_windows
    self.automate(cmd_name='UtilShowStata', value=1)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 493, in automate
    return getattr(self.stata, cmd_name)(value, **kwargs)
AttributeError: 'StataSession' object has no attribute 'stata'
[I 09:56:39.903 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
Traceback (most recent call last):
  File "C:\Users\denze\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\denze\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\denze\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 484, in initialize
    self.init_kernel()
  File "C:\Users\denze\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\kernel.py", line 73, in __init__
    self.stata = StataSession(self, self.conf)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 86, in __init__
    self.init_windows()
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 159, in init_windows
    self.automate(cmd_name='UtilShowStata', value=1)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 493, in automate
    return getattr(self.stata, cmd_name)(value, **kwargs)
AttributeError: 'StataSession' object has no attribute 'stata'
[I 09:56:48.928 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
Traceback (most recent call last):
  File "C:\Users\denze\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\denze\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\denze\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 484, in initialize
    self.init_kernel()
  File "C:\Users\denze\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\kernel.py", line 73, in __init__
    self.stata = StataSession(self, self.conf)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 86, in __init__
    self.init_windows()
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 159, in init_windows
    self.automate(cmd_name='UtilShowStata', value=1)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 493, in automate
    return getattr(self.stata, cmd_name)(value, **kwargs)
AttributeError: 'StataSession' object has no attribute 'stata'
[I 09:56:57.964 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
Traceback (most recent call last):
  File "C:\Users\denze\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\denze\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\denze\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 484, in initialize
    self.init_kernel()
  File "C:\Users\denze\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\kernel.py", line 73, in __init__
    self.stata = StataSession(self, self.conf)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 86, in __init__
    self.init_windows()
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 159, in init_windows
    self.automate(cmd_name='UtilShowStata', value=1)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 493, in automate
    return getattr(self.stata, cmd_name)(value, **kwargs)
AttributeError: 'StataSession' object has no attribute 'stata'
[I 09:57:07.013 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
Traceback (most recent call last):
  File "C:\Users\denze\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\denze\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\denze\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 484, in initialize
    self.init_kernel()
  File "C:\Users\denze\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\kernel.py", line 73, in __init__
    self.stata = StataSession(self, self.conf)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 86, in __init__
    self.init_windows()
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 159, in init_windows
    self.automate(cmd_name='UtilShowStata', value=1)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 493, in automate
    return getattr(self.stata, cmd_name)(value, **kwargs)
AttributeError: 'StataSession' object has no attribute 'stata'
[I 09:57:16.041 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
Traceback (most recent call last):
  File "C:\Users\denze\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\denze\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\denze\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 484, in initialize
    self.init_kernel()
  File "C:\Users\denze\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\denze\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\kernel.py", line 73, in __init__
    self.stata = StataSession(self, self.conf)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 86, in __init__
    self.init_windows()
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 159, in init_windows
    self.automate(cmd_name='UtilShowStata', value=1)
  File "C:\Users\denze\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 493, in automate
    return getattr(self.stata, cmd_name)(value, **kwargs)
AttributeError: 'StataSession' object has no attribute 'stata'
[I 09:57:23.926 NotebookApp] Interrupted...
[I 09:57:23.926 NotebookApp] Shutting down 1 kernel
[I 09:57:25.017 NotebookApp] Kernel shutdown: cf9805f9-9d45-4c8e-826e-d9ddbef955f1

```

**Comment by kylebarron** [comment]
Uh oh, that's awkward

**Comment by lordflaron** [comment]
Thanks so much!
