### ISSUE TITLE
STATA IC on the Mac

### ISSUE THREAD

**Issue by lordflaron** [kylebarron/stata_kernel#282]
Is it possible to use Stata IC with the kernel? As I understand, IC doesn't come with a console version, but can it work with somehow invoking the GUI?

**Comment by kylebarron** [comment]
You can set the execution mode to "automation", though I think it's considerably slower. 
https://kylebarron.github.io/stata_kernel/using_stata_kernel/configuration/#execution_mode

I don't know why Stata IC wouldn't include the console version?

**Comment by lordflaron** [comment]
Apparently it's not a premium enough of a version?

Setting it to automation leads to an error about needing to activate StataIC? 

Do you want the traceback as well?

**Comment by kylebarron** [comment]
It's fixed on master. 
```
pip install git+https://github.com/kylebarron/stata_kernel --upgrade
```

**Comment by kylebarron** [comment]
It seems that Stata prints output to the GUI much slower on Mac than on Windows, and so that's why automation mode is so slow on a mac

**Comment by adrianagaviria88** [comment]
Sorry, installing the git master branch and changing to automation still leads to the same problem. Here's the traceback:

```
Traceback (most recent call last):
  File "/Users/adrianagaviria/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/adrianagaviria/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/adrianagaviria/anaconda3/lib/python3.7/site-packages/stata_kernel/__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "/Users/adrianagaviria/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/Users/adrianagaviria/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/adrianagaviria/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 484, in initialize
    self.init_kernel()
  File "/Users/adrianagaviria/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "/Users/adrianagaviria/anaconda3/lib/python3.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/Users/adrianagaviria/anaconda3/lib/python3.7/site-packages/stata_kernel/kernel.py", line 73, in __init__
    self.stata = StataSession(self, self.conf)
  File "/Users/adrianagaviria/anaconda3/lib/python3.7/site-packages/stata_kernel/stata_session.py", line 89, in __init__
    self.init_mac_automation()
  File "/Users/adrianagaviria/anaconda3/lib/python3.7/site-packages/stata_kernel/stata_session.py", line 165, in init_mac_automation
    self.automate(cmd_name='activate')
  File "/Users/adrianagaviria/anaconda3/lib/python3.7/site-packages/stata_kernel/stata_session.py", line 513, in automate
    raise OSError(res.stderr.decode('utf-8') + '\nInput: ' + cmd)
OSError: 26:27: syntax error: Se esperaba final de línea pero se encontró “"”. (-2741)

Input: tell application "StataIC"" to activate
```

**Comment by kylebarron** [comment]
You have an extra " there. Try putting the path to Stata in the configuration file without quotes

**Comment by lordflaron** [comment]
oh man... that was dumb, sorry for that. It worked. Thank you for your help!

**Comment by mcaceresb** [comment]
@lordflaron By the way, I have Stata 13 IC for Unix and that comes with a console. Surprised that is not the case in OSX. Perhaps the path to the executable is non-obvious? (e.g. `/usr/local/bin/stata` or something along those lines?)

**Comment by kylebarron** [comment]
Nope, Stata IC on Mac doesn't come with a console version, see https://github.com/kylebarron/stata_kernel/issues/189#issuecomment-423013078. Honestly I'm guessing StataCorp just forgot to include it with the Mac IC distribution.

**Comment by lordflaron** [comment]
Yeah, I was pretty surprised myself, but I have Linux so I didn't know all
these challenges when I was writing up my slides. I use arch, btw.

**Comment by kylebarron** [comment]
And you probably didn't expect me to introduce a bug in the released windows version either!

**Comment by mcaceresb** [comment]
> I use arch, btw.

@kylebarron: See? Everyone uses Arch. Take the plunge, all the cool kinds are doing it!

**Comment by lordflaron** [comment]
@kylebarron 

> And you probably didn't expect me to introduce a bug in the released windows version either!

That's all right, bugs make life more interesting... in a tedious mind-numbing sort of way.

**Comment by kylebarron** [comment]
@lordflaron @mcaceresb 

In case you were wondering why StataCorp doesn't supply a Stata IC console version for Mac (tl;dr "pay more, you guys aren't power users!")

From Stata support:

> Unix operating systems often have an optional graphical user interface so we
> need to include console versions of Stata for all flavors of Stata on those
> systems. 
> 
> The Mac operating system always has a graphical user interface so the console
> version of Stata on the Mac is a special tool that is included for power users.
> The Stata/IC for Mac is designed for regular Stata users and does not include a
> console version.
> 
> Originally the Mac versions of Stata were just like the Windows versions and
> did not have any console support.

**Comment by lordflaron** [comment]
Oh man... No words

**Comment by kylebarron** [comment]
Feel free to email them to address your dissatisfaction. :man_shrugging:
