### ISSUE TITLE
pip install stata_kernel problem

### ISSUE THREAD

**Issue by vernongayle** [kylebarron/stata_kernel#293]
Dear Kyle - many thanks for your prompt response.
unfortunately, despite re-installing I am still having difficulties.
(base) C:\Users\vgayle>python --version
Python 3.7.1

(base) C:\Users\vgayle>pip install stata_kernel
Collecting stata_kernel
  Downloading https://files.pythonhosted.org/packages/53/3f/3931d0dc2b41192b37def7bf26b7a515a1187f47042d77d753b045958013/stata_kernel-1.10.5-py3-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 7.7kB/s
Collecting pexpect>=4.6.0 (from stata_kernel)
  Downloading https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 20kB/s
Requirement already satisfied: ipykernel>=4.8.2 in c:\users\vgayle\anaconda3\lib\site-packages (from stata_kernel) (5.1.0)
Requirement already satisfied: requests>=2.19.1 in c:\users\vgayle\anaconda3\lib\site-packages (from stata_kernel) (2.21.0)
Requirement already satisfied: beautifulsoup4>=4.6.3 in c:\users\vgayle\anaconda3\lib\site-packages (from stata_kernel) (4.6.3)
Requirement already satisfied: pywin32>=223; platform_system == "Windows" in c:\users\vgayle\anaconda3\lib\site-packages (from stata_kernel) (223)
Requirement already satisfied: jupyter-client>=5.2.3 in c:\users\vgayle\anaconda3\lib\site-packages (from stata_kernel) (5.2.4)
Requirement already satisfied: pandas>=0.22.0 in c:\users\vgayle\anaconda3\lib\site-packages (from stata_kernel) (0.23.4)
Requirement already satisfied: IPython>=6.5.0 in c:\users\vgayle\anaconda3\lib\site-packages (from stata_kernel) (7.2.0)
Requirement already satisfied: pillow>=5.2.0 in c:\users\vgayle\anaconda3\lib\site-packages (from stata_kernel) (5.3.0)
Requirement already satisfied: pygments>=2.2.0 in c:\users\vgayle\anaconda3\lib\site-packages (from stata_kernel) (2.3.1)
Requirement already satisfied: jupyter>=1.0.0 in c:\users\vgayle\anaconda3\lib\site-packages (from stata_kernel) (1.0.0)
Requirement already satisfied: packaging>=17.1 in c:\users\vgayle\anaconda3\lib\site-packages (from stata_kernel) (18.0)
Collecting ptyprocess>=0.5 (from pexpect>=4.6.0->stata_kernel)
  Downloading https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 331, in _error_catcher
    yield
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 413, in read
    data = self._fp.read(amt)
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\vgayle\Anaconda3\lib\http\client.py", line 447, in read
    n = self.readinto(b)
  File "C:\Users\vgayle\Anaconda3\lib\http\client.py", line 491, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\vgayle\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\vgayle\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\vgayle\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 143, in main
    status = self.run(options, args)
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_internal\resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_internal\resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_internal\resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 283, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_internal\download.py", line 836, in unpack_url
    progress_bar=progress_bar
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_internal\download.py", line 673, in unpack_http_url
    progress_bar)
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_internal\download.py", line 897, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_internal\download.py", line 617, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_internal\utils\hashes.py", line 48, in check_against_chunks
    for chunk in chunks:
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_internal\download.py", line 585, in written_chunks
    for chunk in chunks:
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_internal\download.py", line 574, in resp_read
    decode_content=False):
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 465, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 430, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\vgayle\Anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\vgayle\Anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 336, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by kylebarron** [comment]
That looks like one of the downloads failed. Have you tried that multiple times? Are you behind a firewall of some sort?

**Comment by kylebarron** [comment]
You might also want to try
```
pip install --default-timeout=100 stata_kernel
```
From: https://stackoverflow.com/a/43560499

Not sure why this is necessary. Perhaps your internet is slow to resolve paths or something.

**Comment by kylebarron** [comment]
I'm going to close this in hope that it worked for you. Let me know if it hasn't
