### ISSUE TITLE
No connection to kernel

### ISSUE THREAD

**Issue by mgutierrezc** [kylebarron/stata_kernel#317]
Hi. I am a trying to create a notebook with the stata_kernel, but, for some reason, there is no connection to the kernel. This is the message that is being shown by the console

-I followed again the installation steps in order to solve this issue (including the Windows-specific steps) with no results
-I also tried upgrading the stata_kernel package 

```
[E 00:51:59.639 NotebookApp] Uncaught exception GET /api/kernels/f9849532-5d84-41a7-9f7a-24a0c9469a81/channels?session_id=D27239FAB2B64CA7A47D54EE5759C040 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/f9849532-5d84-41a7-9f7a-24a0c9469a81/channels?session_id=D27239FAB2B64CA7A47D54EE5759C040', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "D:\Anaconda5.2.0\lib\site-packages\tornado\websocket.py", line 546, in _run_callback
        result = callback(*args, **kwargs)
      File "D:\Anaconda5.2.0\lib\site-packages\notebook\services\kernels\handlers.py", line 258, in open
        super(ZMQChannelsHandler, self).open()
      File "D:\Anaconda5.2.0\lib\site-packages\notebook\base\zmqhandlers.py", line 168, in open
        self.send_ping, self.ping_interval, io_loop=loop,
    TypeError: __init__() got an unexpected keyword argument 'io_loop'
```

**Comment by kylebarron** [comment]
Yeah this is something upstream with Jupyter, and out of my scope. Try checking out these 

https://stackoverflow.com/q/48090119
https://github.com/jupyter/notebook/issues/3568
