### ISSUE TITLE
Space in path breaks log cleaning

### ISSUE THREAD

**Issue by alanzchen** [kylebarron/stata_kernel#318]
#### Problem description

When the current working directory contains white spaces, log cleaning fails and the entire kernel dies.

Juypter notebook console:

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "/usr/local/lib/python3.7/site-packages/stata_kernel/kernel.py", line 125, in do_execute
    text_to_run, md5, text_to_exclude=text_to_exclude)
  File "/usr/local/lib/python3.7/site-packages/stata_kernel/stata_session.py", line 274, in do
    self.kernel.cleanTail("`{0}'".format(md5), self.prompt_dot)
  File "/usr/local/lib/python3.7/site-packages/stata_kernel/kernel.py", line 359, in cleanTail
    with open(logfile, 'r+', encoding='utf-8') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/alan/Library/Mobile'

```

I launched Jupyter Lab in `~/Workspace/`, which is a soft-link to `~/Library/Mobile Documents/com~apple~CloudDocs/Workspace/`.

#### Debugging log

```
[?1h=
  ___  ____  ____  ____  ____ (R)
 /__    /   ____/   /   ____/
___/   /   /___/   /   /___/   15.1   Copyright 1985-2017 StataCorp LLC
  Statistics/Data Analysis            StataCorp
                                      4905 Lakeway Drive
     Special Edition                  College Station, Texas 77845 USA
                                      800-STATA-PC        http://www.stata.com
                                      979-696-4600        stata@stata.com
                                      979-696-4601 (fax)

100-student Stata lab perpetual license:
       Serial number:  401506209499
         Licensed to:  Alan Chen
                       

Notes:
      1.  Unicode is supported; see help unicode_advice.
      2.  Maximum number of variables is set to 5000; see help set_maxvar.

. adopath + `"/usr/local/lib/python3.7/site-packages/stata_kernel/ado"'
cd `"/Users/alan/Library/Mobile Documents/com~apple~CloudDocs/Workspace/PA HW"'
set more on
set pagesize 100
set linesize 255
clear all
global stata_kernel_graph_counter = 0

di "$S_DATE, $S_TIME"
di "Stata version: `c(version)'"
di "OS: $S_OS"
`finished_init_cmd'
adopath + `"/usr/local/lib/python3.7/site-packages/stata_kernel/ado"'
  [1]  (BASE)      "/Applications/Stata/ado/base/"
  [2]  (SITE)      "/Applications/ado/"
  [3]              "."
  [4]  (PERSONAL)  "/Users/alan/Library/Application Support/Stata/ado/personal/"
  [5]  (PLUS)      "/Users/alan/Library/Application Support/Stata/ado/plus/"
  [6]  (OLDPLACE)  "~/ado/"
  [7]              "/usr/local/lib/python3.7/site-packages/stata_kernel/ado"

. cd `"/Users/alan/Library/Mobile Documents/com~apple~CloudDocs/Workspace/PA HW"'
/Users/alan/Library/Mobile Documents/com~apple~CloudDocs/Workspace/PA HW

. set more on

. set pagesize 100

. set linesize 255

. clear all

. global stata_kernel_graph_counter = 0

. 
. di "$S_DATE, $S_TIME"
 4 Nov 2019, 21:31:58

. di "Stata version: `c(version)'"
Stata version: 15.1

. di "OS: $S_OS"
OS: Unix

. `finished_init_cmd'
. di "`c(stata_version)'"
`done'
di "`c(stata_version)'"
15.1

. `done'
. _StataKernelCompletions
`bcc4869c9c119320f7af8a3981776720'
_StataKernelCompletions
%mata%

      # bytes   type                        name and extent
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
%varlist%

%globals%
stata_kernel_graph_counter S_ADO S_level F1 F2 F7 F8 S_StataSE S_CONSOLE S_FLAVOR S_OS S_MACH
%logfiles%
%scalars%

%programs%
  ado      792  _StataKernelCompletions
  ado      242  clear.clearreturn
  ado      603  clear._clear_9
  ado     1622  clear
      --------
          3259

%matrices%


. `bcc4869c9c119320f7af8a3981776720'
. mata : invtokens(st_dir("local", "macro", "*")')
`08a286cef0dc100f5df674f2b5353f29'
mata : invtokens(st_dir("local", "macro", "*")')
  

. `08a286cef0dc100f5df674f2b5353f29'
. include /Users/alan/.stata_kernel_cache/include.do
`84d89c91cc0aa7dd2bfc40d61af9e55b'
include /Users/alan/.stata_kernel_cache/include.do

. cap di "Set _rc to 0 initially"

. . `84d89c91cc0aa7dd2bfc40d61af9e55b'
. set more off
`667775c0ed1c17763bb77a9bd7e24e89'
set more off

. `667775c0ed1c17763bb77a9bd7e24e89'
. include /Users/alan/.stata_kernel_cache/include.do
`cc64df03024327541235dabb93f09e00'
include /Users/alan/.stata_kernel_cache/include.do

. tempname __user_rc

. local `__user_rc' = _rc

. . `cc64df03024327541235dabb93f09e00'
. _StataKernelLog off
`25222c9f47f7fdc660ba522f7a53d380'
_StataKernelLog off

. `25222c9f47f7fdc660ba522f7a53d380'
. di `c(linesize)'
`83b14c3154752dfbf1b0322b89ffcf55'
di `c(linesize)'
255

. `83b14c3154752dfbf1b0322b89ffcf55'
. pwd
`9003d1df22eb4d3820015070385194c8'
pwd
/Users/alan/Library/Mobile Documents/com~apple~CloudDocs/Workspace/PA HW

. `9003d1df22eb4d3820015070385194c8'
. _StataKernelCompletions
`bcc4869c9c119320f7af8a3981776720'
_StataKernelCompletions
%mata%

      # bytes   type                        name and extent
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
%varlist%

%globals%
stata_kernel_graph_counter S_ADO S_level F1 F2 F7 F8 S_StataSE S_CONSOLE S_FLAVOR S_OS S_MACH
%logfiles%
%scalars%

%programs%
  ado     1271  _StataKernelLog
  ado      792  _StataKernelCompletions
  ado      242  clear.clearreturn
  ado      603  clear._clear_9
  ado     1622  clear
      --------
          4530

%matrices%


. `bcc4869c9c119320f7af8a3981776720'
. mata : invtokens(st_dir("local", "macro", "*")')
`08a286cef0dc100f5df674f2b5353f29'
mata : invtokens(st_dir("local", "macro", "*")')
  __000000 __user_rc

. `08a286cef0dc100f5df674f2b5353f29'
. macro list `:all globals'
`acf5410dffcb668adf37da696e87d400'
macro list `:all globals'
stata_kernel_graph_counter:
                0
S_ADO:          BASE;SITE;.;PERSONAL;PLUS;OLDPLACE;`"/usr/local/lib/python3.7/site-packages/stata_kernel/ado"'
S_level:        95
F1:             help advice;
F2:             describe;
F7:             save
F8:             use
S_StataSE:      SE
S_CONSOLE:      console
S_FLAVOR:       Intercooled
S_OS:           Unix
S_MACH:         Macintosh (Intel 64-bit)

. `acf5410dffcb668adf37da696e87d400'
. _StataKernelLog on
`d450cfde56d6cad2042c8f0870cc76f5'
_StataKernelLog on

. `d450cfde56d6cad2042c8f0870cc76f5'
. include /Users/alan/.stata_kernel_cache/include.do
`d1d0b5544eadcba44c5f1aa5695588da'
include /Users/alan/.stata_kernel_cache/include.do

. _StataKernelResetRC, num(``__user_rc'')

. macro drop _`__user_rc'

. macro drop ___user_rc

. . `d1d0b5544eadcba44c5f1aa5695588da'
. use births.dta
`a292eda02922aec1f9f461275f0301bd'
use births.dta

. `a292eda02922aec1f9f461275f0301bd'
. include /Users/alan/.stata_kernel_cache/include.do
`cc64df03024327541235dabb93f09e00'
include /Users/alan/.stata_kernel_cache/include.do

. tempname __user_rc

. local `__user_rc' = _rc

. . `cc64df03024327541235dabb93f09e00'
. _StataKernelLog off
`25222c9f47f7fdc660ba522f7a53d380'
_StataKernelLog off

. `25222c9f47f7fdc660ba522f7a53d380'
. di `c(linesize)'
`83b14c3154752dfbf1b0322b89ffcf55'
di `c(linesize)'
255

. `83b14c3154752dfbf1b0322b89ffcf55'
. pwd
`9003d1df22eb4d3820015070385194c8'
pwd
/Users/alan/Library/Mobile Documents/com~apple~CloudDocs/Workspace/PA HW

. `9003d1df22eb4d3820015070385194c8'
. _StataKernelCompletions
`bcc4869c9c119320f7af8a3981776720'
_StataKernelCompletions
%mata%

      # bytes   type                        name and extent
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
%varlist%
stname state year lnbrate REPEAL unemrate pcinc pctnonwh educ_ba educ_hs lnbrat2034 lnbrat1519 lnbrat3544
%globals%
S_FNDATE S_FN stata_kernel_graph_counter S_ADO S_level F1 F2 F7 F8 S_StataSE S_CONSOLE S_FLAVOR S_OS S_MACH
%logfiles%
%scalars%

%programs%
  ado      274  _StataKernelResetRC
  ado     1271  _StataKernelLog
  ado      792  _StataKernelCompletions
  ado      242  clear.clearreturn
  ado      603  clear._clear_9
  ado     1622  clear
      --------
          4804

%matrices%


. `bcc4869c9c119320f7af8a3981776720'
. mata : invtokens(st_dir("local", "macro", "*")')
`08a286cef0dc100f5df674f2b5353f29'
mata : invtokens(st_dir("local", "macro", "*")')
  __000001 __user_rc

. `08a286cef0dc100f5df674f2b5353f29'
. macro list `:all globals'
`acf5410dffcb668adf37da696e87d400'
macro list `:all globals'
S_FNDATE:        3 May 2009 21:18
S_FN:           births.dta
stata_kernel_graph_counter:
                0
S_ADO:          BASE;SITE;.;PERSONAL;PLUS;OLDPLACE;`"/usr/local/lib/python3.7/site-packages/stata_kernel/ado"'
S_level:        95
F1:             help advice;
F2:             describe;
F7:             save
F8:             use
S_StataSE:      SE
S_CONSOLE:      console
S_FLAVOR:       Intercooled
S_OS:           Unix
S_MACH:         Macintosh (Intel 64-bit)

. `acf5410dffcb668adf37da696e87d400'
. _StataKernelLog on
`d450cfde56d6cad2042c8f0870cc76f5'
_StataKernelLog on

. `d450cfde56d6cad2042c8f0870cc76f5'
. include /Users/alan/.stata_kernel_cache/include.do
`d1d0b5544eadcba44c5f1aa5695588da'
include /Users/alan/.stata_kernel_cache/include.do

. _StataKernelResetRC, num(``__user_rc'')

. macro drop _`__user_rc'

. macro drop ___user_rc

. . `d1d0b5544eadcba44c5f1aa5695588da'
. 

```

#### Code Sample

```stata
log using log.log, text replace
```

**Comment by alanzchen** [comment]
I can confirm that by moving the directory to a path without space will resolve this problem.

**Comment by kylebarron** [comment]
Yeah, I'm aware this is a problem. I don't have access to Stata anymore, however. So I'd accept a PR but can't test out a fix myself.

**Comment by alanzchen** [comment]
Where do you think the problem might be? Is it the communication between Python and Stata?

**Comment by kylebarron** [comment]
I'm not exactly sure, to be honest. I'd have to step through the code line by line kinda. It looks like @mcaceresb contributed this part

**Comment by mcaceresb** [comment]
@alanzchen I believe the issue is with log file parsing in the completions engine. [Here](https://github.com/kylebarron/stata_kernel/blob/master/stata_kernel/kernel.py#L357) the kernel tries to open the log file and spaces make it fail. That gets parsed by [this function](https://github.com/kylebarron/stata_kernel/blob/master/stata_kernel/completions.py#L438-L472).

So I think that parsing has some bug that causes it to parse spaces incorrectly. In particular, the list of open log files is newline-separated, and it is cleaned in [this line](https://github.com/kylebarron/stata_kernel/blob/master/stata_kernel/completions.py#L448) using [this regex](https://github.com/kylebarron/stata_kernel/blob/master/stata_kernel/completions.py#L63). There must be a bug in that regex.

**Comment by mcaceresb** [comment]
@alanzchen Let me know if you can try [this fix](https://github.com/kylebarron/stata_kernel/pull/319)? It fixed the issue on my system at least.
