### ISSUE TITLE
AttributeError: 'StataSession' object has no attribute 'log_fd'

### ISSUE THREAD

**Issue by jeremysze** [kylebarron/stata_kernel#334]
#### Problem description

I am actually not quite sure what happened. I was able to use Stata kernel with no issues on Wednesday. But today when I started it up I was not able to get the kernel running. I've tried updating it, as well as uninstalling and reinstalling. 

My first initial error was that the stata path was missing. And I fixed that by going into .stata_kernel.conf and adding the path.
stata_path = C:\Program Files\Stata16\StataMP-64.exe

But I am at my wits end with the next issue. 

#### Debugging log

I checked the .stata_kernel_cache folder but its empty. This is what I got from Anaconda Prompt

(geo) C:\>jupyter lab
[I 10:46:51.364 LabApp] JupyterLab extension loaded from C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\jupyterlab
[I 10:46:51.364 LabApp] JupyterLab application directory is C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\share\jupyter\lab
[I 10:46:51.817 LabApp] Serving notebooks from local directory: C:\
[I 10:46:51.817 LabApp] The Jupyter Notebook is running at:
[I 10:46:51.819 LabApp] http://localhost:8888/?token=3f5aa44e47461c963aac6e79655ee26ca4b907188543f143
[I 10:46:51.820 LabApp]  or http://127.0.0.1:8888/?token=3f5aa44e47461c963aac6e79655ee26ca4b907188543f143
[I 10:46:51.822 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:46:52.069 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/js6666/AppData/Roaming/jupyter/runtime/nbserver-13928-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=3f5aa44e47461c963aac6e79655ee26ca4b907188543f143
     or http://127.0.0.1:8888/?token=3f5aa44e47461c963aac6e79655ee26ca4b907188543f143
[I 10:46:55.441 LabApp] Build is up to date
[I 10:46:59.912 LabApp] Kernel started: 155670a8-1635-4fdb-a050-fc318df6299b
Traceback (most recent call last):
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\ipykernel\kernelapp.py", line 542, in initialize
    self.init_kernel()
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\ipykernel\kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\kernel.py", line 71, in __init__
    self.stata = StataSession(self)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\stata_session.py", line 117, in __init__
    self.do(dedent(init_cmd), md5='finished_init_cmd', display=False)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\stata_session.py", line 263, in do
    child = self.log_fd
AttributeError: 'StataSession' object has no attribute 'log_fd'
[I 10:47:08.883 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
Traceback (most recent call last):
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\ipykernel\kernelapp.py", line 542, in initialize
    self.init_kernel()
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\ipykernel\kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\kernel.py", line 71, in __init__
    self.stata = StataSession(self)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\stata_session.py", line 117, in __init__
    self.do(dedent(init_cmd), md5='finished_init_cmd', display=False)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\stata_session.py", line 263, in do
    child = self.log_fd
AttributeError: 'StataSession' object has no attribute 'log_fd'
[I 10:47:17.896 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
Traceback (most recent call last):
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\ipykernel\kernelapp.py", line 542, in initialize
    self.init_kernel()
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\ipykernel\kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\kernel.py", line 71, in __init__
    self.stata = StataSession(self)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\stata_session.py", line 117, in __init__
    self.do(dedent(init_cmd), md5='finished_init_cmd', display=False)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\stata_session.py", line 263, in do
    child = self.log_fd
AttributeError: 'StataSession' object has no attribute 'log_fd'
[I 10:47:26.930 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
Traceback (most recent call last):
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\ipykernel\kernelapp.py", line 542, in initialize
    self.init_kernel()
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\ipykernel\kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\kernel.py", line 71, in __init__
    self.stata = StataSession(self)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\stata_session.py", line 117, in __init__
    self.do(dedent(init_cmd), md5='finished_init_cmd', display=False)
  File "C:\Users\js6666\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\stata_kernel\stata_session.py", line 263, in do
    child = self.log_fd
AttributeError: 'StataSession' object has no attribute 'log_fd'
[I 10:47:35.962 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports

#### Other information

If you didn't attach the debugging log, please provide:

Windows 10
Stata 16 MP
Stata_kernel 1.11.2

**Comment by kylebarron** [comment]
If you revert to an earlier version does that fix it?
```
pip uninstall stata-kernel
pip install stata-kernel==1.10.5
```

**Comment by jeremysze** [comment]
I just tried that. And its back to `ValueError: stata_path option in configuration file is missing or invalid` error. When I checked the .stata_kernel.conf file, I find that the path is not missing.

**Comment by jeremysze** [comment]
Do you know any other thing I could do to fix this issue?

**Comment by jeremysze** [comment]
I uninstalling the kernel and removed any remnants of stata_kernel. I re-register Stata following this https://www.stata.com/automation/#install and then following the instructions on your getting started page. But now it seems I cant even open a notebook. I am getting an "Error Invalid response: 403 Forbidden"

**Comment by kylebarron** [comment]
Can you open a Python notebook?

**Comment by jeremysze** [comment]
Man.. That isnt working as well.

**Comment by kylebarron** [comment]
I'm guessing you're having local dependency issues or something. I think first you need to figure out how to get a Python notebook working, and then maybe try reinstalling stata kernel version 1.10.5. That version hasn't been updated in a year, so nothing would've changed. If that works, you can try installing the latest stata kernel version.

**Comment by jeremysze** [comment]
Thanks. I think at this point. I'm going to uninstall anaconda and start a fresh.

**Comment by jeremysze** [comment]
I just reinstalled anaconda and stata kernel version 1.10.5. And I am getting a "ValueError: stata_path option in configuration file is missing or invalid"

When I search for ".stata_kernel.conf" file, it seems I have a few of those created. I'm not sure why but here is what I have inside. It seems to have stata_path already filled. 

```
[stata_kernel]

# Path to stata executable. If you type this in your terminal, it should
# start the Stata console
stata_path = C:\Program Files\Stata16\StataMP-64.exe

# **macOS only**
# The manner in which the kernel connects to Stata. Either 'console' or
# 'automation'. 'console' is the default because it allows multiple
# independent sessions of Stata at the same time.
execution_mode = automation

# Directory to hold temporary images and log files
cache_directory = ~/.stata_kernel_cache

# Whether autocompletion suggestions should include the closing symbol
# (i.e. ``'`` for a local macro or `}` if the global starts with `${`)
autocomplete_closing_symbol = False

# Extension and format for images
graph_format = svg

# Scaling factor for graphs
graph_scale = 1

# List of user-created keywords that produce graphs.
# Should be comma-delimited.
user_graph_keywords = coefplot,vioplot
```

**Comment by jeremysze** [comment]
I actually found another .stata_kernel.conf file. Which only has execution_mode defined and added in `stata_path = C:\Program Files\Stata16\StataMP-64.exe`. But now I get the error 

`FileNotFoundError: [Errno 2] No such file or directory: 'c\\.stata_kernel_cache\\log0.log'`

**Comment by kylebarron** [comment]
When the kernel starts it looks for `.stata_kernel.conf` in your home directory. So it sounds like you have multiple and the one in your home directory only has `execution_mode` defined. It's looking in the wrong place for your log file because you don't have `cache_directory` defined. I can't remember exactly which of the fields are necessary, but you should just paste what you pasted above in that file, or re-run `stata_kernel.install`.

**Comment by jeremysze** [comment]
I have added it in and made it specified to an exact path. I also tried re-running stata_kernel.install

```
[stata_kernel]
execution_mode = automation
stata_path = C:/Program Files/Stata16/StataMP-64.exe
cache_directory = C:/c/.stata_kernel_cache
```

But I am still getting an error `FileNotFoundError: [Errno 2] No such file or directory: 'c\\.stata_kernel_cache\\log0.log'`

**Comment by kylebarron** [comment]
Well first when you use `/` it converts to `\\` internally, and second is `C:/c/` writable by your user? Why don't you just stick with the default, because it seems to work for all the other Windows users...
```
cache_directory = ~/.stata_kernel_cache
```

**Comment by jeremysze** [comment]
It seems the kernel now does not die when I run jupyter lab and open stata kernel notebook. However, when I have to use another drive (S drive instead of C drive), the `ImportError: DLL load failed while importing error: The specified module could not be found.` error occurs. Do you know if this is caused because it cannot find the .stata_kernel.conf?

**Comment by kylebarron** [comment]
Ok, so it works on C drive, right?

`ImportError: DLL load failed` is a general Python issue, and is outside the scope of this package. I don't use Windows and can't help at all. You might have to change the `PythonPath` or something. I'm sure there's something on StackOverflow to help.

**Comment by jeremysze** [comment]
Thanks for all the help so far! At least its working on the C drive now. At worse, I'll move files out into the C to work.
