### ISSUE TITLE
Hydrogen doesn´t detect stata_kernel

### ISSUE THREAD

**Issue by Chichidimo** [kylebarron/stata_kernel#336]
Hi again, I got confused of thread, i was trying to make stata_kernel work all the time ( maybe this would sound silly, but i'm a new). This is what happen when i try to run something in Atom;

![image](https://user-images.githubusercontent.com/62303001/76911587-e92eec80-688f-11ea-8fb1-5feb12335eac.png)

- Windows 10
- Stata 15
- 1.11.2

**Comment by kylebarron** [comment]
That means that you didn't correctly follow the installation steps. 
https://kylebarron.dev/stata_kernel/getting_started/#package-install

**Comment by Chichidimo** [comment]
I followed the instructions, but maybe i didn´t set the stata_path manually "ValueError: stata_path option in configuration file is missing or invalid". The thing is i don´t know how to do it.

**Comment by kylebarron** [comment]
https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/

**Comment by Chichidimo** [comment]
Which part of my home directory? I'm simply not finding it .

**Comment by kylebarron** [comment]
https://support.microsoft.com/en-us/help/14201/windows-show-hidden-files

**Comment by Chichidimo** [comment]
It is this one?
![image](https://user-images.githubusercontent.com/62303001/76916626-d0c6ce00-689f-11ea-9673-214a72d5ec46.png)
How should i place the stata path?

**Comment by Chichidimo** [comment]
Somehow i fixed that, but now i have this issue:
Traceback (most recent call last): File "D:\Programas\Anaconda\lib\runpy.py", line 183, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "D:\Programas\Anaconda\lib\runpy.py", line 142, in _get_module_details return _get_module_details(pkg_main_name, error) File "D:\Programas\Anaconda\lib\runpy.py", line 109, in _get_module_details import(pkg_name) File "D:\Programas\Anaconda\lib\site-packages\stata_kernel__init__.py", line 5, in from .kernel import StataKernel File "D:\Programas\Anaconda\lib\site-packages\stata_kernel\kernel.py", line 8, in from PIL import Image File "D:\Programas\Anaconda\lib\site-packages\PIL\Image.py", line 69, in from . import _imaging as core ImportError: DLL load failed: No se puede encontrar el m�dulo especificado.

**Comment by Chichidimo** [comment]
I fixed it, thanks
