### ISSUE TITLE
Dead Kernel

### ISSUE THREAD

**Issue by juliacd** [kylebarron/stata_kernel#343]
After installing StataIC and Anaconda recently so its all updated I followed instructions to install Stata_kernel (https://kylebarron.dev/stata_kernel/getting_started/) but the kernel won't connect. The installation runs smoothly and I have turned rmsg off but nothing works and Stata still opens and closes. I get the following message over and over:

[I 18:14:10.480 NotebookApp] JupyterLab extension loaded from /opt/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 18:14:10.480 NotebookApp] JupyterLab application directory is /opt/anaconda3/share/jupyter/lab
[I 18:14:11.274 NotebookApp] Serving notebooks from local directory: /Users/juliadiniz
[I 18:14:11.275 NotebookApp] The Jupyter Notebook is running at:
[I 18:14:11.275 NotebookApp] http://localhost:8888/?token=db5bbd1694e59b611f001d08d40ea56ce71f46737a134661
[I 18:14:11.275 NotebookApp]  or http://127.0.0.1:8888/?token=db5bbd1694e59b611f001d08d40ea56ce71f46737a134661
[I 18:14:11.275 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:14:11.282 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/juliadiniz/Library/Jupyter/runtime/nbserver-1314-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=db5bbd1694e59b611f001d08d40ea56ce71f46737a134661
     or http://127.0.0.1:8888/?token=db5bbd1694e59b611f001d08d40ea56ce71f46737a134661
[I 18:14:16.064 NotebookApp] Creating new notebook in 
[I 18:14:17.052 NotebookApp] Kernel started: 4195a75a-8778-4add-a16e-78ff50a204c3
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "/opt/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "</opt/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-124>", line 2, in initialize
  File "/opt/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 562, in initialize
    self.init_kernel()
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "/opt/anaconda3/lib/python3.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/kernel.py", line 71, in __init__
    self.stata = StataSession(self)
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/stata_session.py", line 92, in __init__
    self.init_console()
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/stata_session.py", line 199, in init_console
    self.child.expect(self.prompt)
  File "/opt/anaconda3/lib/python3.7/site-packages/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)
  File "/opt/anaconda3/lib/python3.7/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/opt/anaconda3/lib/python3.7/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x11caf7d90>
command: /Applications/Stata/StataIC.app/Contents/MacOS/StataIC
args: [b'/Applications/Stata/StataIC.app/Contents/MacOS/StataIC']
buffer (last 100 chars): ''
before (last 100 chars): ''
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 1329
child_fd: 57
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <_io.TextIOWrapper name='/Users/juliadiniz/.stata_kernel_cache/console_debug.log' mode='w' encoding='utf-8'>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: None
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('\\r\\n\\. ')
[I 18:14:50.047 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports

**Comment by kylebarron** [comment]
Can you try
```
pip uninstall stata_kernel
pip install stata_kernel==1.10.5
python -m stata_kernel.install
```
I might have had a breaking change in 1.11.0

**Comment by juliacd** [comment]
Still the same as before:

[I 18:28:56.480 NotebookApp] JupyterLab extension loaded from /opt/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 18:28:56.480 NotebookApp] JupyterLab application directory is /opt/anaconda3/share/jupyter/lab
[I 18:28:57.246 NotebookApp] Serving notebooks from local directory: /Users/juliadiniz
[I 18:28:57.246 NotebookApp] The Jupyter Notebook is running at:
[I 18:28:57.246 NotebookApp] http://localhost:8888/?token=260beaa5c1f81289237cebaaa188c2354910382c7e184adf
[I 18:28:57.247 NotebookApp]  or http://127.0.0.1:8888/?token=260beaa5c1f81289237cebaaa188c2354910382c7e184adf
[I 18:28:57.247 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:28:57.256 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/juliadiniz/Library/Jupyter/runtime/nbserver-1499-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=260beaa5c1f81289237cebaaa188c2354910382c7e184adf
     or http://127.0.0.1:8888/?token=260beaa5c1f81289237cebaaa188c2354910382c7e184adf
[I 18:29:02.715 NotebookApp] Creating new notebook in 
[I 18:29:03.651 NotebookApp] Kernel started: 09c22eae-81ae-4bf7-84e9-e04d0caf0066
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "/opt/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "</opt/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-124>", line 2, in initialize
  File "/opt/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 562, in initialize
    self.init_kernel()
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "/opt/anaconda3/lib/python3.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/kernel.py", line 73, in __init__
    self.stata = StataSession(self, self.conf)
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/stata_session.py", line 91, in __init__
    self.init_console()
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/stata_session.py", line 196, in init_console
    self.child.expect(self.prompt)
  File "/opt/anaconda3/lib/python3.7/site-packages/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)
  File "/opt/anaconda3/lib/python3.7/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/opt/anaconda3/lib/python3.7/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x110dcecd0>
command: /Applications/Stata/StataIC.app/Contents/MacOS/StataIC
args: [b'/Applications/Stata/StataIC.app/Contents/MacOS/StataIC']
buffer (last 100 chars): ''
before (last 100 chars): ''
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 1514
child_fd: 57
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <_io.TextIOWrapper name='/Users/juliadiniz/.stata_kernel_cache/console_debug.log' mode='w' encoding='utf-8'>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: None
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('\\r\\n\\. ')
[I 18:29:36.651 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
[W 18:30:03.721 NotebookApp] Timeout waiting for kernel_info reply from 09c22eae-81ae-4bf7-84e9-e04d0caf0066
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "/opt/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "</opt/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-124>", line 2, in initialize
  File "/opt/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 562, in initialize
    self.init_kernel()
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "/opt/anaconda3/lib/python3.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/kernel.py", line 73, in __init__
    self.stata = StataSession(self, self.conf)
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/stata_session.py", line 91, in __init__
    self.init_console()
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/stata_session.py", line 196, in init_console
    self.child.expect(self.prompt)
  File "/opt/anaconda3/lib/python3.7/site-packages/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)
  File "/opt/anaconda3/lib/python3.7/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/opt/anaconda3/lib/python3.7/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x11c550fd0>
command: /Applications/Stata/StataIC.app/Contents/MacOS/StataIC
args: [b'/Applications/Stata/StataIC.app/Contents/MacOS/StataIC']
buffer (last 100 chars): ''
before (last 100 chars): ''
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 1520
child_fd: 57
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <_io.TextIOWrapper name='/Users/juliadiniz/.stata_kernel_cache/console_debug.log' mode='w' encoding='utf-8'>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: None
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('\\r\\n\\. ')
[I 18:30:09.659 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel 09c22eae-81ae-4bf7-84e9-e04d0caf0066 restarted

**Comment by juliacd** [comment]
stata path in the config file is set as:
 stata_path = '/Applications/Stata/StataIC.app/Contents/MacOS/StataIC/'

**Comment by kylebarron** [comment]
Oh I think I remember the problem... StataCorp is weird and doesn't bundle the terminal version with StataIC on Mac, so your only option is to switch to automation execution mode. See the docs here: https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/#execution_mode

**Comment by juliacd** [comment]
I've changed the config file to automation 

elif platform.system() == 'Windows':
            execution_mode = 'automation'
        else:
            **execution_mode = 'automation'**
            stata_path = self.get_linux_stata_path_variant(stata_path)

Still the same going on. Are there any other files that need to be changed for execution mode?

**Comment by kylebarron** [comment]
You misread the documentation... You're changing the internal python code, you shouldn't do that, and you should undo it, or force reinstall the python package if you don't remember what you changed.

> The configuration file is a plain text file named .stata_kernel.conf and is located in your home directory. You can change any of the package's settings by opening the file and changing the value of any line of the form

Find `~/.stata_kernel.conf`, open it, and change the required lines. You might have to turn on "hidden files" in the finder to see it.

**Comment by juliacd** [comment]
Wonderful it worked! Thank you Kyle

**Comment by arianazzt** [comment]
hello,have something wrong happened:
(base) tongtongtongtongdeMacBook:~ ariana$ jupyter labextension install
An error occured.
ValueError: "/Users/ariana" is not a valid npm package
See the log file for details:  /var/folders/8m/551gv68s76b3yv1_xvkm5tmh0000gn/T/jupyterlab-debug-zdgqivdu.log
(base) tongtongtongtongdeMacBook:~ ariana$

**Comment by arianazzt** [comment]
still something wrong,  thank you for your reply.
Last login: Wed Apr 15 00:05:28 on ttys000
(base) tongtongtongtongdeMacBook:~ ariana$ conda install -c conda-forge nodejs -y
jupyter labextension install jupyterlab-stata-highlight
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(base) tongtongtongtongdeMacBook:~ ariana$ jupyter labextension install jupyterlab-stata-highlight
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /var/folders/8m/551gv68s76b3yv1_xvkm5tmh0000gn/T/jupyterlab-debug-wvagjk_a.log
(base) tongtongtongtongdeMacBook:~ ariana$
