### ISSUE TITLE
Stata kernel cannot be imported

### ISSUE THREAD

**Issue by Micaroca** [kylebarron/stata_kernel#366]
Hello,

I have installed Anaconda and the Stata kernel, however, the kernel 'dies' after I open a document in Jupiter notebook. I have already reinstalled Anaconda and updated de kernel in my terminal by the issue remains. I get the following error (copied and pasted from my terminal):
/Users/micaelarosadio/opt/anaconda3/bin/activate && conda activate /opt/anaconda3/envs/Stata; 
(base) micaelarosadio@MacBook-Pro ~ % . /Users/micaelarosadio/opt/anaconda3/bin/activate && conda activate /opt/anaconda3/envs/Stata; 
(Stata) micaelarosadio@MacBook-Pro ~ % pip install stata_kernel --upgrade
Requirement already up-to-date: stata_kernel in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (1.12.1)
Requirement already satisfied, skipping upgrade: pygments>=2.2.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from stata_kernel) (2.7.2)
Requirement already satisfied, skipping upgrade: requests>=2.19.1 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from stata_kernel) (2.24.0)
Requirement already satisfied, skipping upgrade: jupyter-client>=5.2.3 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from stata_kernel) (6.1.7)
Requirement already satisfied, skipping upgrade: pexpect>=4.6.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from stata_kernel) (4.8.0)
Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.6.3 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from stata_kernel) (4.9.3)
Requirement already satisfied, skipping upgrade: IPython>=6.5.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from stata_kernel) (7.19.0)
Requirement already satisfied, skipping upgrade: pandas>=0.22.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from stata_kernel) (1.1.4)
Requirement already satisfied, skipping upgrade: packaging>=17.1 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from stata_kernel) (20.4)
Requirement already satisfied, skipping upgrade: pillow>=5.2.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from stata_kernel) (8.0.1)
Requirement already satisfied, skipping upgrade: ipykernel>=4.8.2 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from stata_kernel) (5.3.4)
Requirement already satisfied, skipping upgrade: jupyter>=1.0.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from stata_kernel) (1.0.0)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from requests>=2.19.1->stata_kernel) (2.10)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from requests>=2.19.1->stata_kernel) (2020.6.20)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from requests>=2.19.1->stata_kernel) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from requests>=2.19.1->stata_kernel) (1.25.11)
Requirement already satisfied, skipping upgrade: pyzmq>=13 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jupyter-client>=5.2.3->stata_kernel) (19.0.2)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jupyter-client>=5.2.3->stata_kernel) (2.8.1)
Requirement already satisfied, skipping upgrade: traitlets in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jupyter-client>=5.2.3->stata_kernel) (5.0.5)
Requirement already satisfied, skipping upgrade: jupyter-core>=4.6.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jupyter-client>=5.2.3->stata_kernel) (4.6.3)
Requirement already satisfied, skipping upgrade: tornado>=4.1 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jupyter-client>=5.2.3->stata_kernel) (6.1)
Requirement already satisfied, skipping upgrade: ptyprocess>=0.5 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from pexpect>=4.6.0->stata_kernel) (0.6.0)
Requirement already satisfied, skipping upgrade: soupsieve>1.2; python_version >= "3.0" in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from beautifulsoup4>=4.6.3->stata_kernel) (2.0.1)
Requirement already satisfied, skipping upgrade: decorator in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from IPython>=6.5.0->stata_kernel) (4.4.2)
Requirement already satisfied, skipping upgrade: backcall in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from IPython>=6.5.0->stata_kernel) (0.2.0)
Requirement already satisfied, skipping upgrade: setuptools>=18.5 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from IPython>=6.5.0->stata_kernel) (50.3.0.post20201103)
Requirement already satisfied, skipping upgrade: pickleshare in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from IPython>=6.5.0->stata_kernel) (0.7.5)
Requirement already satisfied, skipping upgrade: jedi>=0.10 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from IPython>=6.5.0->stata_kernel) (0.17.2)
Requirement already satisfied, skipping upgrade: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from IPython>=6.5.0->stata_kernel) (3.0.8)
Requirement already satisfied, skipping upgrade: appnope; sys_platform == "darwin" in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from IPython>=6.5.0->stata_kernel) (0.1.0)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from pandas>=0.22.0->stata_kernel) (2020.4)
Requirement already satisfied, skipping upgrade: numpy>=1.15.4 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from pandas>=0.22.0->stata_kernel) (1.19.4)
Requirement already satisfied, skipping upgrade: six in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from packaging>=17.1->stata_kernel) (1.15.0)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from packaging>=17.1->stata_kernel) (2.4.7)
Requirement already satisfied, skipping upgrade: jupyter-console in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jupyter>=1.0.0->stata_kernel) (6.2.0)
Requirement already satisfied, skipping upgrade: notebook in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jupyter>=1.0.0->stata_kernel) (6.1.4)
Requirement already satisfied, skipping upgrade: qtconsole in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jupyter>=1.0.0->stata_kernel) (4.7.7)
Requirement already satisfied, skipping upgrade: nbconvert in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jupyter>=1.0.0->stata_kernel) (6.0.7)
Requirement already satisfied, skipping upgrade: ipywidgets in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jupyter>=1.0.0->stata_kernel) (7.5.1)
Requirement already satisfied, skipping upgrade: ipython-genutils in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from traitlets->jupyter-client>=5.2.3->stata_kernel) (0.2.0)
Requirement already satisfied, skipping upgrade: parso<0.8.0,>=0.7.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jedi>=0.10->IPython>=6.5.0->stata_kernel) (0.7.1)
Requirement already satisfied, skipping upgrade: wcwidth in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython>=6.5.0->stata_kernel) (0.2.5)
Requirement already satisfied, skipping upgrade: Send2Trash in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from notebook->jupyter>=1.0.0->stata_kernel) (1.5.0)
Requirement already satisfied, skipping upgrade: prometheus-client in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from notebook->jupyter>=1.0.0->stata_kernel) (0.8.0)
Requirement already satisfied, skipping upgrade: terminado>=0.8.3 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from notebook->jupyter>=1.0.0->stata_kernel) (0.9.1)
Requirement already satisfied, skipping upgrade: argon2-cffi in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from notebook->jupyter>=1.0.0->stata_kernel) (20.1.0)
Requirement already satisfied, skipping upgrade: nbformat in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from notebook->jupyter>=1.0.0->stata_kernel) (5.0.8)
Requirement already satisfied, skipping upgrade: jinja2 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from notebook->jupyter>=1.0.0->stata_kernel) (2.11.2)
Requirement already satisfied, skipping upgrade: qtpy in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from qtconsole->jupyter>=1.0.0->stata_kernel) (1.9.0)
Requirement already satisfied, skipping upgrade: pandocfilters>=1.4.1 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from nbconvert->jupyter>=1.0.0->stata_kernel) (1.4.3)
Requirement already satisfied, skipping upgrade: bleach in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from nbconvert->jupyter>=1.0.0->stata_kernel) (3.2.1)
Requirement already satisfied, skipping upgrade: nbclient<0.6.0,>=0.5.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from nbconvert->jupyter>=1.0.0->stata_kernel) (0.5.1)
Requirement already satisfied, skipping upgrade: jupyterlab-pygments in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from nbconvert->jupyter>=1.0.0->stata_kernel) (0.1.2)
Requirement already satisfied, skipping upgrade: mistune<2,>=0.8.1 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from nbconvert->jupyter>=1.0.0->stata_kernel) (0.8.4)
Requirement already satisfied, skipping upgrade: testpath in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from nbconvert->jupyter>=1.0.0->stata_kernel) (0.4.4)
Requirement already satisfied, skipping upgrade: entrypoints>=0.2.2 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from nbconvert->jupyter>=1.0.0->stata_kernel) (0.3)
Requirement already satisfied, skipping upgrade: defusedxml in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from nbconvert->jupyter>=1.0.0->stata_kernel) (0.6.0)
Requirement already satisfied, skipping upgrade: widgetsnbextension~=3.5.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from ipywidgets->jupyter>=1.0.0->stata_kernel) (3.5.1)
Requirement already satisfied, skipping upgrade: cffi>=1.0.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from argon2-cffi->notebook->jupyter>=1.0.0->stata_kernel) (1.14.3)
Requirement already satisfied, skipping upgrade: jsonschema!=2.5.0,>=2.4 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from nbformat->notebook->jupyter>=1.0.0->stata_kernel) (3.2.0)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jinja2->notebook->jupyter>=1.0.0->stata_kernel) (1.1.1)
Requirement already satisfied, skipping upgrade: webencodings in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from bleach->nbconvert->jupyter>=1.0.0->stata_kernel) (0.5.1)
Requirement already satisfied, skipping upgrade: nest-asyncio in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter>=1.0.0->stata_kernel) (1.4.2)
Requirement already satisfied, skipping upgrade: async-generator in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter>=1.0.0->stata_kernel) (1.10)
Requirement already satisfied, skipping upgrade: pycparser in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from cffi>=1.0.0->argon2-cffi->notebook->jupyter>=1.0.0->stata_kernel) (2.20)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0->stata_kernel) (20.2.0)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0->stata_kernel) (2.0.0)
Requirement already satisfied, skipping upgrade: pyrsistent>=0.14.0 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0->stata_kernel) (0.17.3)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /opt/anaconda3/envs/Stata/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0->stata_kernel) (3.4.0)
(Stata) micaelarosadio@MacBook-Pro ~ % jupyter notebook
[I 22:33:44.446 NotebookApp] Serving notebooks from local directory: /Users/micaelarosadio
[I 22:33:44.446 NotebookApp] Jupyter Notebook 6.1.4 is running at:
[I 22:33:44.446 NotebookApp] http://localhost:8888/?token=cdd59b9d683e8e6b46362753f6448fc6d00444083ebba778
[I 22:33:44.447 NotebookApp]  or http://127.0.0.1:8888/?token=cdd59b9d683e8e6b46362753f6448fc6d00444083ebba778
[I 22:33:44.447 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:33:44.452 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/micaelarosadio/Library/Jupyter/runtime/nbserver-9589-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=cdd59b9d683e8e6b46362753f6448fc6d00444083ebba778
     or http://127.0.0.1:8888/?token=cdd59b9d683e8e6b46362753f6448fc6d00444083ebba778
[W 22:33:45.656 NotebookApp] 404 GET /api/kernels/b2cc9ad3-9096-4824-b228-fd898d27a16b/channels?session_id=a17532dcbb9240da85b0161d25b1f5ac (::1): Kernel does not exist: b2cc9ad3-9096-4824-b228-fd898d27a16b
[W 22:33:45.676 NotebookApp] 404 GET /api/kernels/b2cc9ad3-9096-4824-b228-fd898d27a16b/channels?session_id=a17532dcbb9240da85b0161d25b1f5ac (::1) 23.53ms referer=None
[I 22:33:48.545 NotebookApp] Creating new notebook in 
[I 22:33:49.594 NotebookApp] Kernel started: 650a44fe-4c04-4e58-8757-7a9c75529004, name: stata
Cannot import kernel
Traceback (most recent call last):
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__main__.py", line 2, in <module>
    from . import StataKernel
ImportError: cannot import name 'StataKernel' from 'stata_kernel' (/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__init__.py)
[I 22:33:52.594 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Cannot import kernel
Traceback (most recent call last):
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__main__.py", line 2, in <module>
    from . import StataKernel
ImportError: cannot import name 'StataKernel' from 'stata_kernel' (/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__init__.py)
[I 22:33:55.599 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Cannot import kernel
Traceback (most recent call last):
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__main__.py", line 2, in <module>
    from . import StataKernel
ImportError: cannot import name 'StataKernel' from 'stata_kernel' (/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__init__.py)
[I 22:33:58.604 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Cannot import kernel
Traceback (most recent call last):
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__main__.py", line 2, in <module>
    from . import StataKernel
ImportError: cannot import name 'StataKernel' from 'stata_kernel' (/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__init__.py)
[I 22:34:01.613 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Cannot import kernel
Traceback (most recent call last):
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__main__.py", line 2, in <module>
    from . import StataKernel
ImportError: cannot import name 'StataKernel' from 'stata_kernel' (/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__init__.py)
[W 22:34:04.617 NotebookApp] KernelRestarter: restart failed
[W 22:34:04.618 NotebookApp] Kernel 650a44fe-4c04-4e58-8757-7a9c75529004 died, removing from map.
[W 22:34:17.693 NotebookApp] Replacing stale connection: b2cc9ad3-9096-4824-b228-fd898d27a16b:a17532dcbb9240da85b0161d25b1f5ac
[W 22:34:49.636 NotebookApp] Timeout waiting for kernel_info reply from 650a44fe-4c04-4e58-8757-7a9c75529004
[E 22:34:49.638 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 650a44fe-4c04-4e58-8757-7a9c75529004)
[W 22:34:54.049 NotebookApp] 404 GET /api/kernels/650a44fe-4c04-4e58-8757-7a9c75529004/channels?session_id=c7bcda1604bf4dbf83808e833ab2b0d2 (::1): Kernel does not exist: 650a44fe-4c04-4e58-8757-7a9c75529004
[W 22:34:54.050 NotebookApp] 404 GET /api/kernels/650a44fe-4c04-4e58-8757-7a9c75529004/channels?session_id=c7bcda1604bf4dbf83808e833ab2b0d2 (::1) 3.10ms referer=None
[W 22:35:00.576 NotebookApp] Replacing stale connection: 650a44fe-4c04-4e58-8757-7a9c75529004:c7bcda1604bf4dbf83808e833ab2b0d2
[I 22:35:49.595 NotebookApp] Saving file at /Untitled4.ipynb

If anyone has helpful feedback it would be great. I have been struggling with this issue all week. 

Thank you in advance!

**Comment by kylebarron** [comment]
Can you try version `1.12.0`?

**Comment by Micaroca** [comment]
I already tried but it still does not work.
I get the following error message:
/Users/micaelarosadio/opt/anaconda3/bin/activate && conda activate /opt/anaconda3/envs/Stata; 
(base) micaelarosadio@MacBook-Pro ~ % . /Users/micaelarosadio/opt/anaconda3/bin/activate && conda activate /opt/anaconda3/envs/Stata; 
(Stata) micaelarosadio@MacBook-Pro ~ % jupyter notebook
[I 23:22:42.251 NotebookApp] The port 8888 is already in use, trying another port.
[I 23:22:42.254 NotebookApp] Serving notebooks from local directory: /Users/micaelarosadio
[I 23:22:42.254 NotebookApp] Jupyter Notebook 6.1.4 is running at:
[I 23:22:42.254 NotebookApp] http://localhost:8889/?token=f8fa38d0d86da06ab8bd70c8c2be4ef59f471d0ca5a44cb2
[I 23:22:42.254 NotebookApp]  or http://127.0.0.1:8889/?token=f8fa38d0d86da06ab8bd70c8c2be4ef59f471d0ca5a44cb2
[I 23:22:42.254 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:22:42.263 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/micaelarosadio/Library/Jupyter/runtime/nbserver-1005-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=f8fa38d0d86da06ab8bd70c8c2be4ef59f471d0ca5a44cb2
     or http://127.0.0.1:8889/?token=f8fa38d0d86da06ab8bd70c8c2be4ef59f471d0ca5a44cb2
[I 23:22:46.538 NotebookApp] Creating new notebook in 
[I 23:22:47.550 NotebookApp] Kernel started: 9988a09a-5468-4022-9712-165395e3afe9, name: stata
Traceback (most recent call last):
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__init__.py", line 5, in <module>
    from .kernel import StataKernel
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/kernel.py", line 16, in <module>
    from .config import config
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 171, in <module>
    config = Config()
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 86, in __init__
    self.raise_config_error('stata_path')
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 161, in raise_config_error
    raise ValueError(dedent(msg))
ValueError: stata_path option in configuration file is missing or invalid
Refer to the documentation to see how to set it manually:

https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/

[I 23:22:50.551 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__init__.py", line 5, in <module>
    from .kernel import StataKernel
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/kernel.py", line 16, in <module>
    from .config import config
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 171, in <module>
    config = Config()
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 86, in __init__
    self.raise_config_error('stata_path')
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 161, in raise_config_error
    raise ValueError(dedent(msg))
ValueError: stata_path option in configuration file is missing or invalid
Refer to the documentation to see how to set it manually:

https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/

[I 23:22:53.562 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__init__.py", line 5, in <module>
    from .kernel import StataKernel
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/kernel.py", line 16, in <module>
    from .config import config
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 171, in <module>
    config = Config()
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 86, in __init__
    self.raise_config_error('stata_path')
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 161, in raise_config_error
    raise ValueError(dedent(msg))
ValueError: stata_path option in configuration file is missing or invalid
Refer to the documentation to see how to set it manually:

https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/

[I 23:22:56.573 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__init__.py", line 5, in <module>
    from .kernel import StataKernel
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/kernel.py", line 16, in <module>
    from .config import config
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 171, in <module>
    config = Config()
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 86, in __init__
    self.raise_config_error('stata_path')
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 161, in raise_config_error
    raise ValueError(dedent(msg))
ValueError: stata_path option in configuration file is missing or invalid
Refer to the documentation to see how to set it manually:

https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/

[I 23:22:59.581 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/__init__.py", line 5, in <module>
    from .kernel import StataKernel
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/kernel.py", line 16, in <module>
    from .config import config
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 171, in <module>
    config = Config()
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 86, in __init__
    self.raise_config_error('stata_path')
  File "/opt/anaconda3/envs/Stata/lib/python3.7/site-packages/stata_kernel/config.py", line 161, in raise_config_error
    raise ValueError(dedent(msg))
ValueError: stata_path option in configuration file is missing or invalid
Refer to the documentation to see how to set it manually:

https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/

[W 23:23:02.590 NotebookApp] KernelRestarter: restart failed
[W 23:23:02.591 NotebookApp] Kernel 9988a09a-5468-4022-9712-165395e3afe9 died, removing from map.
[W 23:23:47.581 NotebookApp] Timeout waiting for kernel_info reply from 9988a09a-5468-4022-9712-165395e3afe9
[E 23:23:47.585 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 9988a09a-5468-4022-9712-165395e3afe9)
[W 23:23:57.391 NotebookApp] 404 GET /api/kernels/9988a09a-5468-4022-9712-165395e3afe9/channels?session_id=be37162f22bb49b5931a59b906b65539 (::1): Kernel does not exist: 9988a09a-5468-4022-9712-165395e3afe9
[W 23:23:57.409 NotebookApp] 404 GET /api/kernels/9988a09a-5468-4022-9712-165395e3afe9/channels?session_id=be37162f22bb49b5931a59b906b65539 (::1) 21.07ms referer=None
[W 23:24:07.620 NotebookApp] Replacing stale connection: 9988a09a-5468-4022-9712-165395e3afe9:be37162f22bb49b5931a59b906b65539
[I 23:24:52.646 NotebookApp] Saving file at /Untitled5.ipynb

**Comment by kylebarron** [comment]
> ValueError: stata_path option in configuration file is missing or invalid
> Refer to the documentation to see how to set it manually:
> 
> [kylebarron.dev/stata_kernel/using_stata_kernel/configuration](https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/)

looks like your config file is wrong

**Comment by kylebarron** [comment]
> stata_path = "/Applications/Stata/StataIC.app/Contents/MacOS/stata-ic"

that path doesn't exist on your computer. It should be `StataIC` instead of `stata-ic` I think. When it's correct you should be able to paste it in your terminal and open stata

**Comment by Micaroca** [comment]
Yes, I also tried as you proposed it but it did not work (and also tried it in my terminal and Stata opened). I tried just in case with  the lower case ("Stata-ic) as you proposed here https://www.qdxingtu.com/key/Stata%20for%20Mac%20Kernel%20Restarts.html, but both do not work. With stata_path = "/Applications/Stata/StataIC.app/Contents/MacOS/StataIC I get the same error as above.

**Comment by kylebarron** [comment]
Maybe include the path without quotes in the config file. Otherwise feel free to browse old issues but I don't have other suggestions.

**Comment by adityanz** [comment]
I am also having a similar issue ImportError: cannot import name 'StataKernel' from 'stata_kernel' (/Users/aditya/opt/anaconda3/lib/python3.8/site-packages/stata_kernel/__init__.py)
