### ISSUE TITLE
Kernel does not start after upgrade to macOS Big Sur in Atom

### ISSUE THREAD

**Issue by drfwint** [kylebarron/stata_kernel#372]
After upgrading to Big Sur, most of my Hydrogen workflows in atom where broken. I managed to get python and R up and running again, but Stata does not want to cooperate. 

Stata works in jupyterlabs in the browser, so I believe it might be a configuration thing in Atom.

Python 3.9.0
Stata 16.1
Atom 1.53.0
Hydrogen 2.14.6
stata-kernel 1.12.2

So far, I have uninstalled and re-installed the stata_kernel
`pip uninstall stata_kernel`
`pip install stata_kernel`
`python -m stata_kernel.install`

The error message below mentions notebook, which fails to install using `pip install notebook`  because MarkupSafe cannot be installed either.

I now get the following error message when running stata code:

`
Traceback (most recent call last): File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code exec(code, run_globals) File "/usr/local/lib/python3.9/site-packages/stata_kernel/main.py", line 4, in IPKernelApp.launch_instance(kernel_class=StataKernel) File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 844, in launch_instance app.initialize(argv) File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 87, in inner return method(app, args, **kwargs) File "/usr/local/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 582, in initialize self.init_kernel() File "/usr/local/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 444, in init_kernel kernel = kernel_factory(parent=self, session=self.session, File "/usr/local/lib/python3.9/site-packages/traitlets/config/configurable.py", line 537, in instance inst = cls(args, **kwargs)

Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/pkg_resources/init.py", line 343, in get_provider module = sys.modules[moduleOrReq] KeyError: 'notebook'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
`

**Comment by kylebarron** [comment]
I don't see anything in that traceback that concerns `stata-kernel` directly

**Comment by drfwint** [comment]
Thanks for the reply. Obviously still not yet working, though.

**Comment by kylebarron** [comment]
You should probably try to reinstall jupyter. Reinstalling this package doesn't do that
