### ISSUE TITLE
Kernel does not exist

### ISSUE THREAD

**Issue by hackeye** [kylebarron/stata_kernel#381]
win10

stata_kernel + nb_conda_kernels

```
ValueError: check_hostname requires server_hostname
[I 2021-03-25 01:03:10.623 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "D:\anaconda3\envs\stata16\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\stata16\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\stata16\lib\site-packages\stata_kernel\__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "D:\anaconda3\envs\stata16\lib\site-packages\traitlets\config\application.py", line 844, in launch_instance
    app.initialize(argv)
  File "D:\anaconda3\envs\stata16\lib\site-packages\traitlets\config\application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "D:\anaconda3\envs\stata16\lib\site-packages\ipykernel\kernelapp.py", line 582, in initialize
    self.init_kernel()
  File "D:\anaconda3\envs\stata16\lib\site-packages\ipykernel\kernelapp.py", line 444, in init_kernel
    kernel = kernel_factory(parent=self, session=self.session,
  File "D:\anaconda3\envs\stata16\lib\site-packages\traitlets\config\configurable.py", line 537, in instance
    inst = cls(*args, **kwargs)
  File "D:\anaconda3\envs\stata16\lib\site-packages\stata_kernel\kernel.py", line 71, in __init__
    self.stata = StataSession(self)
  File "D:\anaconda3\envs\stata16\lib\site-packages\stata_kernel\stata_session.py", line 75, in __init__
    msg = check_stata_kernel_updated_version(kernel.implementation_version)
  File "D:\anaconda3\envs\stata16\lib\site-packages\stata_kernel\utils.py", line 14, in check_stata_kernel_updated_version
    r = requests.get('https://pypi.org/pypi/stata-kernel/json')
  File "D:\anaconda3\envs\stata16\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\anaconda3\envs\stata16\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda3\envs\stata16\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda3\envs\stata16\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda3\envs\stata16\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\anaconda3\envs\stata16\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\anaconda3\envs\stata16\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\anaconda3\envs\stata16\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\anaconda3\envs\stata16\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "D:\anaconda3\envs\stata16\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\anaconda3\envs\stata16\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\anaconda3\envs\stata16\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\anaconda3\envs\stata16\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
[W 2021-03-25 01:03:13.668 ServerApp] AsyncIOLoopKernelRestarter: restart failed
[W 2021-03-25 01:03:13.668 ServerApp] Kernel f0fa8cef-9687-4fe6-97ed-0681494cf391 died, removing from map.
[W 2021-03-25 01:03:58.538 ServerApp] Timeout waiting for kernel_info reply from f0fa8cef-9687-4fe6-97ed-0681494cf391
[E 2021-03-25 01:03:58.538 ServerApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: f0fa8cef-9687-4fe6-97ed-0681494cf391)
[E 2021-03-25 01:03:58.540 ServerApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: f0fa8cef-9687-4fe6-97ed-0681494cf391)
```

**Comment by kylebarron** [comment]
Your environment is likely messed up. It's failing on 
```py
r = requests.get('https://pypi.org/pypi/stata-kernel/json')
```
which is not an error.

**Comment by hackeye** [comment]
> Your environment is likely messed up.
If I set proxy, it works fine.
```
set http_proxy=http://127.0.0.1:xxxx
set https_proxy=http://127.0.0.1:xxxx
```

**Comment by kylebarron** [comment]
So you're saying you can't load `https://pypi.org/pypi/stata-kernel/json` on your network?

**Comment by hackeye** [comment]
> So you're saying you can't load `https://pypi.org/pypi/stata-kernel/json` on your network?

When I stop proxy, it works fine. 
But when proxy is working, CMD needs to set proxy, to let stata_kernel works fine

**Comment by kylebarron** [comment]
I'm not sure I understand, but I'd accept a PR with a try/except around that request. It's not strictly required; it just shows a message to users when a newer pypi package version exists.
