### ISSUE TITLE
%help magic chokes when parsing retrieved HTML

### ISSUE THREAD

**Issue by ideabucket** [kylebarron/stata_kernel#389]
#### Problem description

When using the `%help` magic, the kernel throws an exception while (it looks like from the logs) trying to parse the HTML fetched from [stata.com/help.cgi](https://www.stata.com/help.cgi?oneway). This results in no output for any invocation of `%help` except the built-in `%help kernel` and `%help magics` commands.

#### Debugging log

[console_debug.log](https://github.com/kylebarron/stata_kernel/files/6371461/console_debug.log)

More saliently this is the python output from stderr of the jupyterlab process:

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
yield gen.maybe_future(handler(stream, idents, msg))
File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
value = future.result()
File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
yielded = ctx_run(next, result)
File "/opt/conda/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 536, in execute_request
self.do_execute(
File "/opt/conda/lib/python3.8/site-packages/stata_kernel/kernel.py", line 110, in do_execute
code = self.magics.magic(code, self)
File "/opt/conda/lib/python3.8/site-packages/stata_kernel/stata_magics.py", line 228, in magic
code = getattr(self, "magic_" + name)(code, kernel)
File "/opt/conda/lib/python3.8/site-packages/stata_kernel/stata_magics.py", line 633, in magic_help
soup.find('a', text='Copyright').find_parent("table").decompose()
AttributeError: 'NoneType' object has no attribute 'find_parent'
```

#### Expected Output

An inline rich-text help as described in the [stata_kernel manual](https://kylebarron.dev/stata_kernel/using_stata_kernel/magics/#help).

#### Other information

It looks from the error output that `stata_magics.py` is trying to parse the DOM tree for an `<a>` element containing the text 'Copyright', but rather than checking whether it found one, just assumes it is present—and then the call to `.find_parent()` is choking, because it’s not.

I am guessing that in a previous version of stata.com/help.cgi <ins>some portion of</ins> the HTML quoted below was wrapped in an `<a>` tag, and that it’s subsequently been rewritten. 

```html
<table border=0 cellpadding=2 cellspacing=0 width="100%">
<tr>
<td valign=top align=center>
<font face="arial,helvetica,helv,sans-serif" size=1>
&copy; Copyright 1996&ndash;2021 StataCorp LLC
&nbsp;&nbsp;&bull;&nbsp;&nbsp;
<a href="/terms-of-use" class="bodylink">Terms of use</a>
&nbsp;&nbsp;&bull;&nbsp;&nbsp;
<a href="/privacy-policy" class="bodylink">Privacy</a>
&nbsp;&nbsp;&bull;&nbsp;&nbsp;
<a href="/company/contact" class="bodylink">Contact us</a>
</font>
</td>
</tr>
</table>
```

I wonder if this is also the cause of #321.

**Comment by mcaceresb** [comment]
@ideabucket Hard to think this  is related to another bug since this only change for the new Stata release (at least the wayback machine shows the Copyright wrapped in an a for help pages last year).

**Comment by ideabucket** [comment]
FWIW, this isn't a Stata 17 change. It happened under Stata 16 as well, I just didn't get around to filing an issue about it until yesterday.

**Comment by mcaceresb** [comment]
@ideabucket Interesting. I found some archived versions from November that still had it in an `a` tag. I guess they changed it  before Stata 17 anyway.

**Comment by gaksaray** [comment]
I am having a similar issue with the %help magic, in particular with %help kernel. I tried different versions of Anaconda distribution (2020.07, 2020.11, and 2021.05) and Stata (15.1, 16.1, and 17) but I get the following error nevertheless:

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\gaksaray\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\gaksaray\anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\gaksaray\anaconda3\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "C:\Users\gaksaray\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 543, in execute_request
    self.do_execute(
  File "C:\Users\gaksaray\anaconda3\lib\site-packages\stata_kernel\kernel.py", line 110, in do_execute
    code = self.magics.magic(code, self)
  File "C:\Users\gaksaray\anaconda3\lib\site-packages\stata_kernel\stata_magics.py", line 228, in magic
    code = getattr(self, "magic_" + name)(code, kernel)
  File "C:\Users\gaksaray\anaconda3\lib\site-packages\stata_kernel\stata_magics.py", line 579, in magic_help
    help_plain = f.read()
  File "C:\Users\gaksaray\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2413: character maps to <undefined>
```
Kernel stops operating and needs to be restarted
![image](https://user-images.githubusercontent.com/72267919/125062261-dbb9f900-e0b6-11eb-8f5f-3393c16b673e.png)
