### ISSUE TITLE
Issues with stata_kernel in Atom (Hydrogen)

### ISSUE THREAD

**Issue by StaffanBetner** [kylebarron/stata_kernel#414]
#### Problem description

I am having troubles importing the kernel in Atom. It works fine in Jupyter!

#### Debugging log

I get this traceback in Atom (user name redacted):

```
Traceback (most recent call last):
  File "C:\Users\xx\Miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xx\Miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xx\Miniconda3\lib\site-packages\stata_kernel__main__.py", line 2, in 
    from . import StataKernel
ImportError: cannot import name 'StataKernel' from 'stata_kernel' (C:\Users\xx\Miniconda3\lib\site-packages\stata_kernel__init__.py)
```

#### Other information

- Operating System
Windows 10
- Stata version
Stata/SE 14
- Package version (You can find this by running `pip show stata_kernel` in your terminal.)
1.12.2-py39hcbf5309_1
- Hydrogen version
2.16.3
- Atom version
1.58.0

**Comment by kylebarron** [comment]
If it works fine in Jupyter, that means the Python environment that Atom is using is different from the global one that Jupyter is using. In that case, the easiest workaround is to set environment variables in your terminal before launching Atom, so that it's pointign to the same Python as Jupyter.

**Comment by StaffanBetner** [comment]
It is the same Python environment. I have setup an R kernel as well which works in both Jupyter and Atom.

**Comment by StaffanBetner** [comment]
After starting Atom within the Anaconda prompt it works. So you were right in some way. Need to figure out how!
